---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.SERVICE_NAME }}-sa'
  namespace: '{{ .Values.NAMESPACE }}'
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-101"
    "helm.sh/hook-delete-policy": "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
    deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
