{{- $tmp1 := required "BACKUP_DAEMON_DBAAS_ACCESS_PASSWORD env variable must be set!" .Values.BACKUP_DAEMON_DBAAS_ACCESS_PASSWORD }}
{{- $tmp2 := required "DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD env variable must be set!" .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD}}
{{- $tmp3 := required "DBAAS_TENANT_PASSWORD env variable must be set!" .Values.DBAAS_TENANT_PASSWORD }}
{{- $tmp4 := required "DBAAS_DB_EDITOR_CREDENTIALS_PASSWORD env variable must be set!" .Values.DBAAS_DB_EDITOR_CREDENTIALS_PASSWORD }}
{{- $tmp5 := required "DISCR_TOOL_USER_PASSWORD env variable must be set!" .Values.DISCR_TOOL_USER_PASSWORD }}
{{- $b64p := tpl (.Files.Get "data/policy.json") $ | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dbaas-security-configuration-secret
  labels:
    app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
    deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
type: Opaque
data:
  "users.json": {{ $b64p }}
