---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.SERVICE_NAME }}'
    labels:
        app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
        deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
spec:
    ports:
    -   name: web
        port: 8080
        targetPort: 8080
        protocol: TCP
    selector:
        name: '{{ .Values.SERVICE_NAME }}'
