{{- $b64p := tpl (.Files.Get "data/service-account-roles.yaml") $ | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dbaas-security-service-account-roles-secret
  labels:
    app.kubernetes.io/name: "{{ .Values.SERVICE_NAME }}"
    deployment.qubership.org/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
type: Opaque
data:
  "service-account-roles.yaml": {{ $b64p }}
