//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Classifier) DeepCopyInto(out *Classifier) {
	*out = *in
	if in.CustomKeys != nil {
		in, out := &in.CustomKeys, &out.CustomKeys
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExtraKeys != nil {
		in, out := &in.ExtraKeys, &out.ExtraKeys
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Classifier.
func (in *Classifier) DeepCopy() *Classifier {
	if in == nil {
		return nil
	}
	out := new(Classifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionProperty) DeepCopyInto(out *ConnectionProperty) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialsSecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraProperties != nil {
		in, out := &in.ExtraProperties, &out.ExtraProperties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionProperty.
func (in *ConnectionProperty) DeepCopy() *ConnectionProperty {
	if in == nil {
		return nil
	}
	out := new(ConnectionProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialsSecretRef) DeepCopyInto(out *CredentialsSecretRef) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]SecretKeyMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialsSecretRef.
func (in *CredentialsSecretRef) DeepCopy() *CredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseAccessPolicy) DeepCopyInto(out *DatabaseAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseAccessPolicy.
func (in *DatabaseAccessPolicy) DeepCopy() *DatabaseAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(DatabaseAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseAccessPolicyList) DeepCopyInto(out *DatabaseAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseAccessPolicyList.
func (in *DatabaseAccessPolicyList) DeepCopy() *DatabaseAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(DatabaseAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseAccessPolicySpec) DeepCopyInto(out *DatabaseAccessPolicySpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]PolicyRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseAccessPolicySpec.
func (in *DatabaseAccessPolicySpec) DeepCopy() *DatabaseAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseAccessPolicyStatus) DeepCopyInto(out *DatabaseAccessPolicyStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseAccessPolicyStatus.
func (in *DatabaseAccessPolicyStatus) DeepCopy() *DatabaseAccessPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseAccessPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretClaim) DeepCopyInto(out *DatabaseSecretClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretClaim.
func (in *DatabaseSecretClaim) DeepCopy() *DatabaseSecretClaim {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseSecretClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretClaimList) DeepCopyInto(out *DatabaseSecretClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseSecretClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretClaimList.
func (in *DatabaseSecretClaimList) DeepCopy() *DatabaseSecretClaimList {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseSecretClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretClaimSpec) DeepCopyInto(out *DatabaseSecretClaimSpec) {
	*out = *in
	in.Classifier.DeepCopyInto(&out.Classifier)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretClaimSpec.
func (in *DatabaseSecretClaimSpec) DeepCopy() *DatabaseSecretClaimSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSecretClaimStatus) DeepCopyInto(out *DatabaseSecretClaimStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	if in.FirstNotFoundAt != nil {
		in, out := &in.FirstNotFoundAt, &out.FirstNotFoundAt
		*out = (*in).DeepCopy()
	}
	if in.LastRotatedAt != nil {
		in, out := &in.LastRotatedAt, &out.LastRotatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSecretClaimStatus.
func (in *DatabaseSecretClaimStatus) DeepCopy() *DatabaseSecretClaimStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseSecretClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDatabase) DeepCopyInto(out *ExternalDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDatabase.
func (in *ExternalDatabase) DeepCopy() *ExternalDatabase {
	if in == nil {
		return nil
	}
	out := new(ExternalDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDatabaseList) DeepCopyInto(out *ExternalDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDatabaseList.
func (in *ExternalDatabaseList) DeepCopy() *ExternalDatabaseList {
	if in == nil {
		return nil
	}
	out := new(ExternalDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDatabaseSpec) DeepCopyInto(out *ExternalDatabaseSpec) {
	*out = *in
	in.Classifier.DeepCopyInto(&out.Classifier)
	if in.ConnectionProperties != nil {
		in, out := &in.ConnectionProperties, &out.ConnectionProperties
		*out = make([]ConnectionProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDatabaseSpec.
func (in *ExternalDatabaseSpec) DeepCopy() *ExternalDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDatabaseStatus) DeepCopyInto(out *ExternalDatabaseStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDatabaseStatus.
func (in *ExternalDatabaseStatus) DeepCopy() *ExternalDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialInstantiation) DeepCopyInto(out *InitialInstantiation) {
	*out = *in
	if in.SourceClassifier != nil {
		in, out := &in.SourceClassifier, &out.SourceClassifier
		*out = new(Classifier)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialInstantiation.
func (in *InitialInstantiation) DeepCopy() *InitialInstantiation {
	if in == nil {
		return nil
	}
	out := new(InitialInstantiation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDatabase) DeepCopyInto(out *InternalDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDatabase.
func (in *InternalDatabase) DeepCopy() *InternalDatabase {
	if in == nil {
		return nil
	}
	out := new(InternalDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InternalDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDatabaseList) DeepCopyInto(out *InternalDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InternalDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDatabaseList.
func (in *InternalDatabaseList) DeepCopy() *InternalDatabaseList {
	if in == nil {
		return nil
	}
	out := new(InternalDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InternalDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDatabaseSpec) DeepCopyInto(out *InternalDatabaseSpec) {
	*out = *in
	in.Classifier.DeepCopyInto(&out.Classifier)
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VersioningConfig != nil {
		in, out := &in.VersioningConfig, &out.VersioningConfig
		*out = new(VersioningConfig)
		**out = **in
	}
	if in.InitialInstantiation != nil {
		in, out := &in.InitialInstantiation, &out.InitialInstantiation
		*out = new(InitialInstantiation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDatabaseSpec.
func (in *InternalDatabaseSpec) DeepCopy() *InternalDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(InternalDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalDatabaseStatus) DeepCopyInto(out *InternalDatabaseStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalDatabaseStatus.
func (in *InternalDatabaseStatus) DeepCopy() *InternalDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(InternalDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroserviceBalancingRule) DeepCopyInto(out *MicroserviceBalancingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroserviceBalancingRule.
func (in *MicroserviceBalancingRule) DeepCopy() *MicroserviceBalancingRule {
	if in == nil {
		return nil
	}
	out := new(MicroserviceBalancingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroserviceBalancingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroserviceBalancingRuleAppliedRule) DeepCopyInto(out *MicroserviceBalancingRuleAppliedRule) {
	*out = *in
	if in.Microservices != nil {
		in, out := &in.Microservices, &out.Microservices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroserviceBalancingRuleAppliedRule.
func (in *MicroserviceBalancingRuleAppliedRule) DeepCopy() *MicroserviceBalancingRuleAppliedRule {
	if in == nil {
		return nil
	}
	out := new(MicroserviceBalancingRuleAppliedRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroserviceBalancingRuleItem) DeepCopyInto(out *MicroserviceBalancingRuleItem) {
	*out = *in
	if in.Microservices != nil {
		in, out := &in.Microservices, &out.Microservices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroserviceBalancingRuleItem.
func (in *MicroserviceBalancingRuleItem) DeepCopy() *MicroserviceBalancingRuleItem {
	if in == nil {
		return nil
	}
	out := new(MicroserviceBalancingRuleItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroserviceBalancingRuleList) DeepCopyInto(out *MicroserviceBalancingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicroserviceBalancingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroserviceBalancingRuleList.
func (in *MicroserviceBalancingRuleList) DeepCopy() *MicroserviceBalancingRuleList {
	if in == nil {
		return nil
	}
	out := new(MicroserviceBalancingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicroserviceBalancingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroserviceBalancingRuleSpec) DeepCopyInto(out *MicroserviceBalancingRuleSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MicroserviceBalancingRuleItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroserviceBalancingRuleSpec.
func (in *MicroserviceBalancingRuleSpec) DeepCopy() *MicroserviceBalancingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(MicroserviceBalancingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicroserviceBalancingRuleStatus) DeepCopyInto(out *MicroserviceBalancingRuleStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	if in.AppliedRules != nil {
		in, out := &in.AppliedRules, &out.AppliedRules
		*out = make([]MicroserviceBalancingRuleAppliedRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicroserviceBalancingRuleStatus.
func (in *MicroserviceBalancingRuleStatus) DeepCopy() *MicroserviceBalancingRuleStatus {
	if in == nil {
		return nil
	}
	out := new(MicroserviceBalancingRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBalancingRule) DeepCopyInto(out *NamespaceBalancingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBalancingRule.
func (in *NamespaceBalancingRule) DeepCopy() *NamespaceBalancingRule {
	if in == nil {
		return nil
	}
	out := new(NamespaceBalancingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceBalancingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBalancingRuleAppliedRule) DeepCopyInto(out *NamespaceBalancingRuleAppliedRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBalancingRuleAppliedRule.
func (in *NamespaceBalancingRuleAppliedRule) DeepCopy() *NamespaceBalancingRuleAppliedRule {
	if in == nil {
		return nil
	}
	out := new(NamespaceBalancingRuleAppliedRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBalancingRuleItem) DeepCopyInto(out *NamespaceBalancingRuleItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBalancingRuleItem.
func (in *NamespaceBalancingRuleItem) DeepCopy() *NamespaceBalancingRuleItem {
	if in == nil {
		return nil
	}
	out := new(NamespaceBalancingRuleItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBalancingRuleList) DeepCopyInto(out *NamespaceBalancingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceBalancingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBalancingRuleList.
func (in *NamespaceBalancingRuleList) DeepCopy() *NamespaceBalancingRuleList {
	if in == nil {
		return nil
	}
	out := new(NamespaceBalancingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceBalancingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBalancingRuleSpec) DeepCopyInto(out *NamespaceBalancingRuleSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]NamespaceBalancingRuleItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBalancingRuleSpec.
func (in *NamespaceBalancingRuleSpec) DeepCopy() *NamespaceBalancingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceBalancingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBalancingRuleStatus) DeepCopyInto(out *NamespaceBalancingRuleStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	if in.AppliedRules != nil {
		in, out := &in.AppliedRules, &out.AppliedRules
		*out = make([]NamespaceBalancingRuleAppliedRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBalancingRuleStatus.
func (in *NamespaceBalancingRuleStatus) DeepCopy() *NamespaceBalancingRuleStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceBalancingRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBinding) DeepCopyInto(out *NamespaceBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBinding.
func (in *NamespaceBinding) DeepCopy() *NamespaceBinding {
	if in == nil {
		return nil
	}
	out := new(NamespaceBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBindingList) DeepCopyInto(out *NamespaceBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NamespaceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBindingList.
func (in *NamespaceBindingList) DeepCopy() *NamespaceBindingList {
	if in == nil {
		return nil
	}
	out := new(NamespaceBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NamespaceBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBindingSpec) DeepCopyInto(out *NamespaceBindingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBindingSpec.
func (in *NamespaceBindingSpec) DeepCopy() *NamespaceBindingSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceBindingStatus) DeepCopyInto(out *NamespaceBindingStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceBindingStatus.
func (in *NamespaceBindingStatus) DeepCopy() *NamespaceBindingStatus {
	if in == nil {
		return nil
	}
	out := new(NamespaceBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorStatus) DeepCopyInto(out *OperatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorStatus.
func (in *OperatorStatus) DeepCopy() *OperatorStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermanentBalancingRule) DeepCopyInto(out *PermanentBalancingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermanentBalancingRule.
func (in *PermanentBalancingRule) DeepCopy() *PermanentBalancingRule {
	if in == nil {
		return nil
	}
	out := new(PermanentBalancingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PermanentBalancingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermanentBalancingRuleAppliedRule) DeepCopyInto(out *PermanentBalancingRuleAppliedRule) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermanentBalancingRuleAppliedRule.
func (in *PermanentBalancingRuleAppliedRule) DeepCopy() *PermanentBalancingRuleAppliedRule {
	if in == nil {
		return nil
	}
	out := new(PermanentBalancingRuleAppliedRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermanentBalancingRuleItem) DeepCopyInto(out *PermanentBalancingRuleItem) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermanentBalancingRuleItem.
func (in *PermanentBalancingRuleItem) DeepCopy() *PermanentBalancingRuleItem {
	if in == nil {
		return nil
	}
	out := new(PermanentBalancingRuleItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermanentBalancingRuleList) DeepCopyInto(out *PermanentBalancingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PermanentBalancingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermanentBalancingRuleList.
func (in *PermanentBalancingRuleList) DeepCopy() *PermanentBalancingRuleList {
	if in == nil {
		return nil
	}
	out := new(PermanentBalancingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PermanentBalancingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermanentBalancingRuleSpec) DeepCopyInto(out *PermanentBalancingRuleSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PermanentBalancingRuleItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermanentBalancingRuleSpec.
func (in *PermanentBalancingRuleSpec) DeepCopy() *PermanentBalancingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PermanentBalancingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermanentBalancingRuleStatus) DeepCopyInto(out *PermanentBalancingRuleStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	if in.AppliedRules != nil {
		in, out := &in.AppliedRules, &out.AppliedRules
		*out = make([]PermanentBalancingRuleAppliedRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermanentBalancingRuleStatus.
func (in *PermanentBalancingRuleStatus) DeepCopy() *PermanentBalancingRuleStatus {
	if in == nil {
		return nil
	}
	out := new(PermanentBalancingRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRole) DeepCopyInto(out *PolicyRole) {
	*out = *in
	if in.AdditionalRole != nil {
		in, out := &in.AdditionalRole, &out.AdditionalRole
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRole.
func (in *PolicyRole) DeepCopy() *PolicyRole {
	if in == nil {
		return nil
	}
	out := new(PolicyRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyMapping) DeepCopyInto(out *SecretKeyMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyMapping.
func (in *SecretKeyMapping) DeepCopy() *SecretKeyMapping {
	if in == nil {
		return nil
	}
	out := new(SecretKeyMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRole) DeepCopyInto(out *ServiceRole) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRole.
func (in *ServiceRole) DeepCopy() *ServiceRole {
	if in == nil {
		return nil
	}
	out := new(ServiceRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersioningConfig) DeepCopyInto(out *VersioningConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersioningConfig.
func (in *VersioningConfig) DeepCopy() *VersioningConfig {
	if in == nil {
		return nil
	}
	out := new(VersioningConfig)
	in.DeepCopyInto(out)
	return out
}
