apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 30
resourceRefs:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: dbaas
    name: dbaas-aggregator
    ref: aggregator
assertAll:
  - celExpr: "aggregator.status.readyReplicas == 2"
  - celExpr: "aggregator.spec.strategy.type == 'RollingUpdate'"
