apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 60
resourceRefs:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: ${DBAAS_NAMESPACE}
    name: dbaas-aggregator
    ref: aggregator
  - apiVersion: apps/v1
    kind: Deployment
    namespace: ${DBAAS_NAMESPACE}
    name: dbaas-operator
    ref: operator
  - apiVersion: apps/v1
    kind: Deployment
    namespace: ${PG_NAMESPACE}
    name: dbaas-postgres-adapter
    ref: adapter
collectors:
  - type: pod
    selector: name=dbaas-aggregator
    namespace: ${DBAAS_NAMESPACE}
    tail: 200
  - type: command
    command: kubectl -n ${DBAAS_NAMESPACE} describe deployment dbaas-aggregator
  - type: command
    command: kubectl -n ${DBAAS_NAMESPACE} describe deployment dbaas-operator
  - type: command
    command: kubectl -n ${PG_NAMESPACE} describe deployment dbaas-postgres-adapter
assertAll:
  - celExpr: "aggregator.spec.replicas == 2"
  - celExpr: "aggregator.status.readyReplicas == 2"
  - celExpr: "aggregator.spec.strategy.type == 'RollingUpdate'"
  - celExpr: "operator.status.readyReplicas >= 1"
  - celExpr: "adapter.status.readyReplicas >= 1"
