apiVersion: dbaas.netcracker.com/v1
kind: DbMicroserviceBalancingRule
metadata:
  name: microservice-balancing-rules
  namespace: dbaas-system
spec:
  rules:
    - type: postgresql
      label: zone=fast
      microservices:
        - billing-service
