apiVersion: dbaas.netcracker.com/v1
kind: PermanentBalancingRule
metadata:
  name: permanent-balancing-rules
  namespace: dbaas-system
spec:
  rules:
    - dbType: postgresql
      physicalDatabaseId: postgresql-prod-a
      namespaces:
        - dbaas-system
    - dbType: mongodb
      physicalDatabaseId: mongodb-prod-a
      namespaces:
        - dbaas-system
    - dbType: cassandra
      physicalDatabaseId: cassandra-prod-a
      namespaces:
        - dbaas-system
