apiVersion: dbaas.netcracker.com/v1
kind: MicroserviceBalancingRule
metadata:
  name: microservice-balancing-rules
  namespace: dbaas-system
spec:
  rules:
    - type: postgresql
      label: zone=fast
      microservices:
        - billing-service
    - type: mongodb
      label: tier=standard
      microservices:
        - notification-service
