apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.SERVICE_NAME }}-stub'
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    {{- if .Values.DEPLOYMENT_SESSION_ID }}
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
    {{- end }}