kind: Deployment
apiVersion: apps/v1
metadata:
    name: '{{ .Values.SERVICE_NAME }}'
    labels:
        name: '{{ .Values.SERVICE_NAME }}'
        app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
        app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
        app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
        app.kubernetes.io/component: 'backend'
        app.kubernetes.io/technology: 'java-quarkus'
        netcracker.cloud/disaster-recovery.manageable: 'true'
        deployment.netcracker.com/sessionId: {{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}
spec:
    replicas: {{ .Values.REPLICAS | default 1 }}
    strategy:
{{ if  (.Values.DBAAS_RECREATE_DEPLOYMENT_STRATEGY) }}
        type: Recreate
{{ else }}
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
{{ end }}
    template:
        metadata:
            labels:
                name: '{{ .Values.SERVICE_NAME }}'
                app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
                app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
                app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
                app.kubernetes.io/component: 'backend'
                app.kubernetes.io/technology: 'java-quarkus'
                netcracker.cloud/disaster-recovery.manageable: 'true'
                deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}'
        spec:
            nodeSelector:
              {{ .Values.NODE_SELECTOR_DBAAS_KEY }}: '{{ .Values.REGION_DBAAS}}'
            serviceAccountName: '{{ .Values.SERVICE_NAME }}'
            volumes:
              - name: dbaas-security-volume
                secret:
                  secretName: dbaas-security-configuration-secret
            containers:
              - name: '{{ .Values.SERVICE_NAME }}'
                image: '{{ .Values.IMAGE_REPOSITORY }}:{{ .Values.TAG }}'
                volumeMounts:
                  -   name: dbaas-security-volume
                      mountPath: '{{ .Values.DBAAS_SECURITY_CONFIGURATION_LOCATION }}'
                      readOnly: true
                args:
                  - --health-probe-bind-address=:'{{ .Values.HEALTH_PROBE_BIND_ADDRESS }}'
                  - --metrics-bind-address='{{ .Values.METRICS_BIND_ADDRESS }}
                  - --watch-namespaces='{{ .Values.WATCH_NAMESPACE }}'
                  - --leader-elect
                env:
                  - name: DBAAS_SECURITY_CONFIGURATION_LOCATION
                    value: '{{ .Values.DBAAS_SECURITY_CONFIGURATION_LOCATION }}'
                  - name: DBAAS_AGGREGATOR_USERNAME
                    value: '{{ .Values.DBAAS_AGGREGATOR_USERNAME }}'
                ports:
                  - name: web
                    containerPort: 8081
                    protocol: TCP
                livenessProbe:
                    httpGet:
                      path: /healthz
                      port: web
                    initialDelaySeconds: {{ .Values.LIVENESS_PROBE_INITIAL_DELAY_SECONDS }}
                    periodSeconds: 20
                readinessProbe:
                    httpGet:
                      path: /readyz
                      port: web
                    initialDelaySeconds: 5
                    periodSeconds: 10
                securityContext:
                    readOnlyRootFilesystem: {{ .Values.READONLY_CONTAINER_FILE_SYSTEM_ENABLED }}
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                          - ALL
                resources:
                    requests:
                        cpu: '{{ .Values.CPU_REQUEST }}'
                        memory: '{{ .Values.MEMORY_LIMIT }}'
                    limits:
                        cpu: '{{ .Values.CPU_LIMIT }}'
                        memory: '{{ .Values.MEMORY_LIMIT }}'
    selector:
      matchLabels:
        name: '{{ .Values.SERVICE_NAME }}'
