apiVersion: dbaas.netcracker.com/v1
kind: ExternalDatabase
metadata:
  name: externaldatabase-sample
spec:
  classifier:
    namespace: dbaas-system
    microserviceName: sample-service
    scope: service
  type: postgresql
  dbName: sample-db
  connectionProperties:
    - role: admin
      extraProperties:
        host: postgres-host
        port: "5432"
        url: "jdbc:postgresql://postgres-host:5432/sample-db"
