apiVersion: dbaas.netcracker.com/v1
kind: DbNamespaceBalancingRule
metadata:
  name: namespace-balancing-rules
spec:
  rules:
    - name: pg-sample
      type: postgresql
      physicalDatabaseId: postgresql-sample
      order: 0
    - name: mongo-sample
      type: mongodb
      physicalDatabaseId: mongodb-sample
      order: 1
