apiVersion: dbaas.netcracker.com/v1
kind: InternalDatabase
metadata:
  labels:
    app.kubernetes.io/name: dbaas-operator
    app.kubernetes.io/managed-by: kustomize
  name: internaldatabase-sample
spec:
  classifier:
    microserviceName: sample-service
    scope: service
  type: postgresql
