## Append samples of your project ##
resources:
- dbaas_v1_internaldatabase.yaml
- dbaas_v1_microservicebalancingrule.yaml
- dbaas_v1_namespacebalancingrule.yaml
- dbaas_v1_permanentbalancingrule.yaml
- dbaas_v1_databaseaccesspolicy.yaml
- dbaas_v1_externaldatabase.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
