{{- if .Values.SAMPLE_SERVICE_ENABLED }}
{{- range .Values.SECRET_CLAIMS }}
---
apiVersion: dbaas.netcracker.com/v1
kind: DatabaseSecretClaim
metadata:
  name: '{{ .claimName }}'
  namespace: '{{ $.Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/name: '{{ $.Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ $.Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ $.Values.MANAGED_BY }}'
spec:
  classifier:
    microserviceName: '{{ $.Values.SERVICE_NAME }}'
    namespace: '{{ $.Values.NAMESPACE }}'
    scope: {{ .scope }}
    {{- if eq .scope "tenant" }}
    tenantId: '{{ $.Values.TENANT_ID }}'
    {{- end }}
  secretName: '{{ .secretName }}'
  type: '{{ $.Values.DB_TYPE }}'
  {{- if .role }}
  userRole: '{{ $.Values.DATABASE_SECRET_USER_ROLE }}'
  {{- end }}
{{- end }}
{{- end }}
