{{- if .Values.SAMPLE_SERVICE_ENABLED }}
apiVersion: dbaas.netcracker.com/v1
kind: InternalDatabase
metadata:
  name: '{{ .Values.INTERNAL_DATABASE_NAME }}'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
spec:
  classifier:
    microserviceName: '{{ .Values.SERVICE_NAME }}'
    namespace: '{{ .Values.NAMESPACE }}'
    scope: service
  type: '{{ .Values.DB_TYPE }}'
{{- end }}
