certificate.store.path=${CERTIFICATE_FILE_PATH:/etc/tls}
quarkus.http.port=8080
quarkus.http.ssl-port=8443
quarkus.http.insecure-requests=enabled
quarkus.tls.https.key-store.pem.0.cert=${certificate.store.path}/tls.crt
quarkus.tls.https.key-store.pem.0.key=${certificate.store.path}/tls.key
quarkus.tls.https.reload-period=${TLS_CERTIFICATE_RELOAD_PERIOD:1h}
quarkus.http.tls-configuration-name=https
