---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databasedeclarations
  - dbpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databasedeclarations/finalizers
  - dbpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databasedeclarations/status
  - dbpolicies/status
  verbs:
  - get
  - patch
  - update
