---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databaseaccesspolicies
  - externaldatabases
  - internaldatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databaseaccesspolicies/status
  - databasesecrets/status
  - externaldatabases/status
  - internaldatabases/status
  - microservicebalancingrules/status
  - namespacebalancingrules/status
  - permanentbalancingrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databasesecrets
  - microservicebalancingrules
  - namespacebalancingrules
  - namespacebindings
  - permanentbalancingrules
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - microservicebalancingrules/finalizers
  - namespacebalancingrules/finalizers
  - namespacebindings/finalizers
  - permanentbalancingrules/finalizers
  verbs:
  - update
