---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databaseaccesspolicies
  - externaldatabases
  - internaldatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databaseaccesspolicies/status
  - databasesecrets/status
  - dbmicroservicebalancingrules/status
  - dbnamespacebalancingrules/status
  - dbpermanentbalancingrules/status
  - externaldatabases/status
  - internaldatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - databasesecrets
  - dbmicroservicebalancingrules
  - dbnamespacebalancingrules
  - dbpermanentbalancingrules
  - namespacebindings
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - dbaas.netcracker.com
  resources:
  - dbmicroservicebalancingrules/finalizers
  - dbnamespacebalancingrules/finalizers
  - dbpermanentbalancingrules/finalizers
  - namespacebindings/finalizers
  verbs:
  - update
