#!/usr/bin/env bash
# Deploys the fixed part of the dbaas-aggregator upgrade/downgrade availability test, staged rather
# than through bootstrap's combined `install-without-test` target, because that target assumes the
# aggregator and operator come from the same checkout — this test deliberately does not:
#
#   - PostgreSQL/Patroni and the PostgreSQL adapter come from the pinned pgskipper-operator checkout
#     through bootstrap's patroni-core and patroni-services targets. Task-specific values disable the
#     pgskipper charts' integration tests so they cannot mutate or restart the fixed database fixture.
#   - The dbaas-aggregator comes from INITIAL_DIR (installed here, with two replicas) and later gets
#     transitioned to TARGET_DIR by transition-aggregator.sh — the only thing that changes during the
#     measured transition.
#   - The dbaas-operator comes from FIXTURE_DIR — always the newer of the two versions under test,
#     regardless of direction — and stays untouched for the rest of the run. Because it is always the
#     newer release, it already supports both the initial and target aggregator's CR contract, so
#     there is nothing version-specific to set up for either direction.
#   - The go-test-app-service sample comes entirely from the HARNESS checkout: its chart (so the
#     InternalDatabase template matches the fixed operator's contract) and its image (so the
#     post-transition check's PUT /postgres/items call reaches a binary that actually has that handler
#     — neither v6.14.1 nor v6.15.0 contains it). API_DBAAS_ADDRESS is the only DBaaS routing value
#     passed to that chart.
#
# Then deploys the continuous availability probe and runs the one-shot pre-transition functional
# check. None of the fixed components are touched again after this script returns — only
# transition-aggregator.sh's `helm upgrade` on the aggregator release runs after this point.
#
# Required environment (all set by the calling workflow step):
#   REPOS_DIR                   - contains pgskipper-operator/ (pinned commit checkout), matching the
#                                  layout bootstrap/Makefile's own `git clone` target expects.
#   INITIAL_DIR, FIXTURE_DIR     - initial-version and fixture-version qubership-dbaas checkouts. Only
#                                  INITIAL_DIR/helm-templates/dbaas-aggregator and
#                                  FIXTURE_DIR/dbaas-operator/helm-templates/dbaas-operator (plus its
#                                  resource-profiles/dev.yaml) are used from them.
#   HARNESS_DIR                  - checkout of the current branch (this script's own repo): scripts,
#                                  values overlay, the sample-service chart/image, and the probe's
#                                  Dockerfile-built image and deployment.yaml.
#   PG_NAMESPACE, DBAAS_NAMESPACE
#   INITIAL_TAG                  - image tag (e.g. v6.14.1) for the initial dbaas-aggregator install.
#   FIXTURE_TAG                  - image tag (e.g. v6.15.0) for the fixed dbaas-operator.
#   GO_IMAGE_REPOSITORY, GO_IMAGE_TAG
#   PROBE_IMAGE_REPOSITORY, PROBE_IMAGE_TAG
#   CREDENTIALS_SECRET          - name of the Secret this script creates with keys username/password.
#   POSTGRES_PASSWORD, DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD, DBAAS_TENANT_PASSWORD,
#   DBAAS_DB_EDITOR_CREDENTIALS_PASSWORD, DISCR_TOOL_USER_PASSWORD, BACKUP_DAEMON_DBAAS_ACCESS_PASSWORD
#                                - generated by the workflow step and already masked there; this script
#                                  never echoes them.
#   ITEM_MARKER                 - unique name for the pre-transition fixture record.
#   FIXTURE_FINGERPRINT_FILE    - path this script writes the captured FIXTURE_FINGERPRINT JSON to, for
#                                  transition-aggregator.sh / evaluate-probes.sh to read back.
#   FIXED_COMPONENT_IMAGES_FILE - path this script writes the initial operator/patroni/adapter/sample
#                                  image references to, for transition-aggregator.sh to confirm none of
#                                  them drifted across the transition.
#   BASELINE_SECONDS            - how long to let the continuous probe run before returning (default 40).
set -euo pipefail

: "${REPOS_DIR:?}" "${HARNESS_DIR:?}" "${INITIAL_DIR:?}" "${FIXTURE_DIR:?}" "${PG_NAMESPACE:?}"
: "${DBAAS_NAMESPACE:?}" "${INITIAL_TAG:?}" "${FIXTURE_TAG:?}"
: "${GO_IMAGE_REPOSITORY:?}" "${GO_IMAGE_TAG:?}" "${PROBE_IMAGE_REPOSITORY:?}" "${PROBE_IMAGE_TAG:?}"
: "${CREDENTIALS_SECRET:?}" "${POSTGRES_PASSWORD:?}" "${DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD:?}"
: "${DBAAS_TENANT_PASSWORD:?}" "${DBAAS_DB_EDITOR_CREDENTIALS_PASSWORD:?}" "${DISCR_TOOL_USER_PASSWORD:?}"
: "${BACKUP_DAEMON_DBAAS_ACCESS_PASSWORD:?}" "${ITEM_MARKER:?}" "${FIXTURE_FINGERPRINT_FILE:?}"
: "${FIXED_COMPONENT_IMAGES_FILE:?}"

BASELINE_SECONDS="${BASELINE_SECONDS:-40}"
DBAAS_VALUES_FILE="$HARNESS_DIR/.github/scripts/dbaas-transition/dbaas-values-transition.yaml"
PATRONI_CORE_VALUES_FILE="$HARNESS_DIR/.github/scripts/dbaas-transition/patroni-core-values-transition.yaml"
# Must set registrationPassword to the same DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD the aggregator gets
# below — bootstrap/patroni-services-values.yaml hardcodes it to the literal "password" instead, which
# would silently break the adapter's registration once the aggregator's own password is randomized.
PATRONI_SERVICES_VALUES_FILE="$HARNESS_DIR/.github/scripts/dbaas-transition/patroni-services-values-transition.yaml"
BOOTSTRAP_MAKE="make -C $HARNESS_DIR/bootstrap CONFIG_FILE=local.mk"
DBAAS_SERVICE_NAME="dbaas-aggregator"
REGION_DBAAS="database"
NODE_SELECTOR_DBAAS_KEY="region"

echo "=== Validating pre-populated checkouts (bootstrap's own git clone must no-op) ==="
for dir in "$REPOS_DIR/pgskipper-operator" "$INITIAL_DIR" "$FIXTURE_DIR"; do
  [ -d "$dir/.git" ] || { echo "Expected an existing git checkout at $dir" >&2; exit 1; }
  echo "$dir -> $(git -C "$dir" rev-parse HEAD)"
done

echo "=== Validating bootstrap prerequisites (helm/git/kubectl/cluster) ==="
$BOOTSTRAP_MAKE validate REPOS_DIR="$REPOS_DIR" PG_NAMESPACE="$PG_NAMESPACE" DBAAS_NAMESPACE="$DBAAS_NAMESPACE"

echo "=== Stage: Patroni core (PostgreSQL), pinned pgskipper checkout ==="
$BOOTSTRAP_MAKE install-patroni-core \
  REPOS_DIR="$REPOS_DIR" PG_NAMESPACE="$PG_NAMESPACE" DBAAS_NAMESPACE="$DBAAS_NAMESPACE" \
  PATRONI_CORE_VALUES_FILE="$PATRONI_CORE_VALUES_FILE" \
  POSTGRES_PASSWORD="$POSTGRES_PASSWORD"

echo "=== Stage: waiting for PostgreSQL readiness ==="
$BOOTSTRAP_MAKE wait-patroni-pods PG_NAMESPACE="$PG_NAMESPACE"

echo "=== Stage: installing the initial-version dbaas-aggregator (2 replicas) ==="
rendered_aggregator_values="$(mktemp)"
TAG="$INITIAL_TAG" DBAAS_SERVICE_NAME="$DBAAS_SERVICE_NAME" REGION_DBAAS="$REGION_DBAAS" \
  NODE_SELECTOR_DBAAS_KEY="$NODE_SELECTOR_DBAAS_KEY" PG_NAMESPACE="$PG_NAMESPACE" \
  KUBERNETES_M2M_ENABLED=true \
  BACKUP_DAEMON_DBAAS_ACCESS_PASSWORD="$BACKUP_DAEMON_DBAAS_ACCESS_PASSWORD" \
  DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD="$DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD" \
  DBAAS_TENANT_PASSWORD="$DBAAS_TENANT_PASSWORD" \
  DBAAS_DB_EDITOR_CREDENTIALS_PASSWORD="$DBAAS_DB_EDITOR_CREDENTIALS_PASSWORD" \
  DISCR_TOOL_USER_PASSWORD="$DISCR_TOOL_USER_PASSWORD" \
  POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
  envsubst < "$DBAAS_VALUES_FILE" > "$rendered_aggregator_values"
helm upgrade --install dbaas-aggregator \
  "$INITIAL_DIR/helm-templates/dbaas-aggregator" \
  --namespace "$DBAAS_NAMESPACE" --create-namespace \
  -f "$rendered_aggregator_values" \
  --wait --timeout 5m
rm -f "$rendered_aggregator_values"

echo "=== Availability prerequisite check: aggregator has 2 ready replicas and a non-Recreate strategy ==="
strategy_type="$(kubectl -n "$DBAAS_NAMESPACE" get deployment dbaas-aggregator -o jsonpath='{.spec.strategy.type}')"
if [ "$strategy_type" = "Recreate" ]; then
  echo "dbaas-aggregator Deployment uses a Recreate strategy — this test requires RollingUpdate" >&2
  exit 1
fi
ready="$(kubectl -n "$DBAAS_NAMESPACE" get deployment dbaas-aggregator -o jsonpath='{.status.readyReplicas}')"
desired="$(kubectl -n "$DBAAS_NAMESPACE" get deployment dbaas-aggregator -o jsonpath='{.spec.replicas}')"
if [ "${ready:-0}" -lt 2 ] || [ "$desired" -ne 2 ]; then
  echo "Expected 2/2 ready replicas on dbaas-aggregator, got ${ready:-0}/${desired:-0}" >&2
  exit 1
fi

echo "=== Stage: installing the fixed dbaas-operator ($FIXTURE_TAG, from the fixture checkout) ==="
rendered_operator_values="$(mktemp)"
DBAAS_OPERATOR_TAG="$FIXTURE_TAG" DBAAS_NAMESPACE="$DBAAS_NAMESPACE" REGION_DBAAS="$REGION_DBAAS" \
  NODE_SELECTOR_DBAAS_KEY="$NODE_SELECTOR_DBAAS_KEY" DBAAS_OPERATOR_ENABLED=true OPERATOR_M2M_ENABLED=true \
  envsubst < "$HARNESS_DIR/bootstrap/dbaas-operator-values.yaml" > "$rendered_operator_values"
helm upgrade --install dbaas-operator \
  "$FIXTURE_DIR/dbaas-operator/helm-templates/dbaas-operator" \
  --namespace "$DBAAS_NAMESPACE" \
  -f "$rendered_operator_values" \
  -f "$FIXTURE_DIR/dbaas-operator/helm-templates/dbaas-operator/resource-profiles/dev.yaml" \
  --wait --timeout 5m
rm -f "$rendered_operator_values"

echo "=== Stage: waiting for the dbaas-operator deployment ==="
$BOOTSTRAP_MAKE wait-dbaas-operator DBAAS_NAMESPACE="$DBAAS_NAMESPACE" DBAAS_OPERATOR_ENABLED=true

echo "=== Stage: patroni-services (PostgreSQL adapter), pinned pgskipper checkout ==="
$BOOTSTRAP_MAKE install-patroni-services \
  REPOS_DIR="$REPOS_DIR" PG_NAMESPACE="$PG_NAMESPACE" DBAAS_NAMESPACE="$DBAAS_NAMESPACE" \
  DBAAS_SERVICE_NAME="$DBAAS_SERVICE_NAME" \
  PATRONI_SERVICES_VALUES_FILE="$PATRONI_SERVICES_VALUES_FILE"

echo "=== Stage: waiting for adapter registration ==="
$BOOTSTRAP_MAKE wait-patroni-services-registration PG_NAMESPACE="$PG_NAMESPACE"

echo "=== Configuring test-only M2M prerequisites (OIDC issuer-discovery), then restarting the aggregator ==="
kubectl create clusterrolebinding dbaas-aggregator-issuer-discovery \
  --clusterrole=system:service-account-issuer-discovery \
  --serviceaccount="$DBAAS_NAMESPACE":dbaas-aggregator \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl -n "$DBAAS_NAMESPACE" rollout restart deployment/dbaas-aggregator
kubectl rollout status deployment/dbaas-aggregator -n "$DBAAS_NAMESPACE" --timeout=300s
kubectl rollout status deployment/dbaas-operator -n "$DBAAS_NAMESPACE" --timeout=300s

echo "=== Deploying go-test-app-service (harness chart + harness-built image) ==="
# API_DBAAS_ADDRESS is the only DBaaS routing value passed to the chart. The test only exercises
# /postgres/ping, /postgres/connection-properties, and /postgres/items, which all resolve through the
# service-scoped (no-role) datasource — restrict INTERNAL_DATABASES to that one entry and drop
# SECRET_CLAIMS entirely (MOUNT_SECRETS=false already means the chart mounts none of them; this also
# stops it from creating unused claim resources and Secret RBAC).
helm upgrade --install go-test-app-service \
  "$HARNESS_DIR/test-apps/go-test-app-service/helm-templates/go-test-app-service" \
  --namespace "$DBAAS_NAMESPACE" \
  --set-json 'INTERNAL_DATABASES=[{"name":"go-test-app-service-postgres","scope":"service"}]' \
  --set-json 'SECRET_CLAIMS=[]' \
  --set IMAGE_REPOSITORY="$GO_IMAGE_REPOSITORY" \
  --set TAG="$GO_IMAGE_TAG" \
  --set IMAGE_PULL_POLICY=Never \
  --set MOUNT_SECRETS=false \
  --set M2M_ENABLED=true \
  --set API_DBAAS_ADDRESS="http://dbaas-aggregator.$DBAAS_NAMESPACE:8080" \
  --wait --timeout 5m
kubectl -n "$DBAAS_NAMESPACE" rollout status deployment/go-test-app-service --timeout=300s

echo "=== Waiting for the service-scoped InternalDatabase to finish provisioning (status.phase=Succeeded) ==="
# The Deployment's readiness/liveness probes only call /health, which never touches PostgreSQL (see
# app.go's handleHealth) — a clean rollout proves the process started, not that the database exists.
# Baseline probing must not start until provisioning genuinely finished, or a slow or failed
# provisioning would be misreported as transition downtime instead of a setup failure.
if ! kubectl -n "$DBAAS_NAMESPACE" wait internaldatabase go-test-app-service-postgres \
    --for=jsonpath='{.status.phase}'=Succeeded --timeout=300s; then
  echo "Service-scoped InternalDatabase did not reach Succeeded within 300s:" >&2
  kubectl -n "$DBAAS_NAMESPACE" describe internaldatabase go-test-app-service-postgres >&2 || true
  echo "--- dbaas-operator logs ---" >&2
  kubectl -n "$DBAAS_NAMESPACE" logs deploy/dbaas-operator --all-containers=true --tail=500 >&2 || true
  echo "--- dbaas-postgres-adapter logs ---" >&2
  kubectl -n "$PG_NAMESPACE" logs deploy/dbaas-postgres-adapter --all-containers=true --tail=500 >&2 || true
  echo "--- Kubernetes events ($DBAAS_NAMESPACE) ---" >&2
  kubectl -n "$DBAAS_NAMESPACE" get events --sort-by=.lastTimestamp >&2 || true
  exit 1
fi

echo "=== Recording initial images of the fixed components (operator, patroni, adapter, sample service) ==="
{
  echo "dbaas-operator=$(kubectl -n "$DBAAS_NAMESPACE" get deployment dbaas-operator -o jsonpath='{.spec.template.spec.containers[0].image}')"
  echo "patroni=$(kubectl -n "$PG_NAMESPACE" get pods -l app=patroni -o jsonpath='{.items[0].spec.containers[0].image}')"
  echo "dbaas-postgres-adapter=$(kubectl -n "$PG_NAMESPACE" get deployment dbaas-postgres-adapter -o jsonpath='{.spec.template.spec.containers[0].image}')"
  echo "go-test-app-service=$(kubectl -n "$DBAAS_NAMESPACE" get deployment go-test-app-service -o jsonpath='{.spec.template.spec.containers[0].image}')"
} > "$FIXED_COMPONENT_IMAGES_FILE"
cat "$FIXED_COMPONENT_IMAGES_FILE"

echo "=== Creating probe credentials Secret (cluster-dba / generated password, never printed) ==="
kubectl -n "$DBAAS_NAMESPACE" create secret generic "$CREDENTIALS_SECRET" \
  --from-literal=username=cluster-dba \
  --from-literal=password="$DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "=== Building and deploying the continuous availability probe ==="
probe_manifest="$(mktemp)"
sed \
  -e "s#__NAMESPACE__#$DBAAS_NAMESPACE#g" \
  -e "s#__IMAGE__#$PROBE_IMAGE_REPOSITORY:$PROBE_IMAGE_TAG#g" \
  -e "s#__CREDENTIALS_SECRET__#$CREDENTIALS_SECRET#g" \
  "$HARNESS_DIR/test-apps/dbaas-availability-probe/deployment.yaml" > "$probe_manifest"
kubectl apply -f "$probe_manifest"
rm -f "$probe_manifest"
kubectl -n "$DBAAS_NAMESPACE" rollout status deployment/dbaas-availability-probe --timeout=120s

echo "=== Initial functional verification (one-shot Job: ping, seed a recognizable record, fingerprint) ==="
kubectl -n "$DBAAS_NAMESPACE" delete job dbaas-fixture-verify --ignore-not-found
verify_manifest="$(mktemp)"
cat > "$verify_manifest" <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: dbaas-fixture-verify
  namespace: $DBAAS_NAMESPACE
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: verify
          image: $PROBE_IMAGE_REPOSITORY:$PROBE_IMAGE_TAG
          imagePullPolicy: Never
          env:
            - name: PROBE_MODE
              value: verify
            - name: AGGREGATOR_URL
              value: http://dbaas-aggregator.$DBAAS_NAMESPACE:8080
            - name: SAMPLE_SERVICE_URL
              value: http://go-test-app-service.$DBAAS_NAMESPACE:8080
            - name: NAMESPACE
              value: $DBAAS_NAMESPACE
            - name: ITEM_MARKER
              value: "$ITEM_MARKER"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ALL]
EOF
kubectl apply -f "$verify_manifest"
rm -f "$verify_manifest"

if ! kubectl -n "$DBAAS_NAMESPACE" wait --for=condition=complete job/dbaas-fixture-verify --timeout=180s; then
  echo "Initial functional verification Job failed or timed out; its log (stderr only shows FIXTURE_ERROR, never credentials):" >&2
  kubectl -n "$DBAAS_NAMESPACE" logs job/dbaas-fixture-verify --all-containers=true >&2 || true
  exit 1
fi

fingerprint_line="$(kubectl -n "$DBAAS_NAMESPACE" logs job/dbaas-fixture-verify | grep '^FIXTURE_FINGERPRINT: ' | sed 's/^FIXTURE_FINGERPRINT: //')"
if [ -z "$fingerprint_line" ]; then
  echo "Initial functional verification Job completed but produced no FIXTURE_FINGERPRINT line" >&2
  exit 1
fi
printf '%s' "$fingerprint_line" > "$FIXTURE_FINGERPRINT_FILE"
echo "Captured pre-transition fixture fingerprint (nonsensitive: item id/name + sanitized connection URL)"

echo "=== Baseline: letting the continuous probe run for ${BASELINE_SECONDS}s before the transition ==="
sleep "$BASELINE_SECONDS"
echo "=== deploy-fixture.sh done ==="
