{
 "title": "DBaaS Dashboard",
 "description": "Shows statistics and health details of selected DBaaS instance on selected cloud: \\n - health status of each adapter and DBaaS aggregator \\n - load factor—number of requests to DBaaS \\n - number of data bases that are and are not registered in DBaaS. If DB wasn’t created by DBaaS but was created directly \\n - it can cause problems for backup and maintenance procedures, so it is important to keep tracking such cases \\n - JVM parameters for each DBaaS adapter and aggregator.",
 "tags": [
  "Java",
  "Prometheus",
  "DbaaS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{}, container)"
    }
   },
   {
    "name": "namespace",
    "label": "DBAAS Project",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{container='$service_name',}, namespace)"
    }
   },
   {
    "name": "adapter",
    "label": "DbaaS adapter",
    "query": {
     "query": "label_values(dbaas_adapter_health{namespace='$namespace', container='$service_name',}, type)"
    }
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "jvm_heap_part",
    "label": "JVM Heap Parts",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace='$namespace', container='$service_name', area='heap',}, id)"
    }
   },
   {
    "name": "jvm_nonheap_part",
    "label": "JVM Non Heap Parts",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace='$namespace', container='$service_name', area='nonheap',}, id)"
    }
   },
   {
    "name": "jvm_buffers_type",
    "label": "JVM Byte Buffer Types",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{namespace='$namespace', container='$service_name',}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "description": "(-1 = UNKNOWN, 0 = OK, 3 = WARN, 6 = PROBLEM, 10 = FATAL)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_running{exported_namespace=\"$namespace\", exported_pod!~\".*deploy\", container=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{namespace=\"$namespace\", container=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Current Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_threads_live_threads{namespace=\"$namespace\", container=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jvm_classes_loaded_classes{namespace=\"$namespace\", container=\"$service_name\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"$service_name\", namespace=\"$namespace\"}[$inter]))",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=\"$service_name\", exported_namespace=\"$namespace\"})",
     "legendFormat": "limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"$service_name\", exported_namespace=\"$namespace\"})",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Commited Memory",
   "type": "timeseries",
   "description": "The amount of used memory (Stack value)",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "avg(container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"$service_name\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(sum(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\"}))",
     "legendFormat": "NonHeap"
    },
    {
     "expr": "avg(sum(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\"}))",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "timeseries",
   "description": "The open file descriptor count (average for current time interval)",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(process_files_open_files{container=\"$service_name\", namespace=\"$namespace\"})",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "Databases Number By Registration",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dbaas_registration_databases_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "legendFormat": "not registered databases"
    },
    {
     "expr": "avg(dbaas_registration_databases_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "legendFormat": "registered databases"
    }
   ]
  },
  {
   "title": "Number Of Databases",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(dbaas_registration_databases_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "legendFormat": "not registered"
    },
    {
     "expr": "avg(dbaas_registration_databases_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "legendFormat": "total registered"
    },
    {
     "expr": "avg(dbaas_registration_databases_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
     "legendFormat": "lost"
    }
   ]
  },
  {
   "title": "Adapter health status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(dbaas_adapter_health{container=\"$service_name\", namespace=\"$namespace\"}) by (type, identifier)",
     "legendFormat": "{{type}} : {{identifier}}"
    }
   ]
  },
  {
   "title": "Adapter Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests to adapter $adapter by operation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "repeat": "adapter",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(dbaas_adapter_database_operation_request_total{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"} - dbaas_adapter_database_operation_request_total{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"} offset $__interval) by (operation, result) OR on() vector(0) ",
       "legendFormat": "{{operation}}: {{result}}"
      }
     ]
    },
    {
     "title": "Duration of operations by adapter $adapter",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "repeat": "adapter",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(increase(dbaas_adapter_database_operation_seconds_sum{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"}[$inter])/increase(dbaas_adapter_database_operation_seconds_count{type=\"$adapter\", container=\"$service_name\", namespace=\"$namespace\"}[$inter]) OR on() vector(0)) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Number of registered databases per adapter type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(dbaas_registration_databases_postgresql_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Postgresql"
      },
      {
       "expr": "avg(dbaas_registration_databases_mongodb_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Mongodb"
      },
      {
       "expr": "avg(dbaas_registration_databases_cassandra_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) ",
       "legendFormat": "Cassandra"
      },
      {
       "expr": "avg(dbaas_registration_databases_opensearch_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "OpenSearch"
      },
      {
       "expr": "avg(dbaas_registration_databases_redis_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Redis"
      }
     ]
    },
    {
     "title": "Number of not registered databases per adapter type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(dbaas_registration_databases_postgresql_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Postgresql"
      },
      {
       "expr": "avg(dbaas_registration_databases_mongodb_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Mongodb"
      },
      {
       "expr": "avg(dbaas_registration_databases_cassandra_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) ",
       "legendFormat": "Cassandra"
      },
      {
       "expr": "avg(dbaas_registration_databases_opensearch_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "OpenSearch"
      },
      {
       "expr": "avg(dbaas_registration_databases_redis_ghost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Redis"
      }
     ]
    },
    {
     "title": "Number of lost databases per adapter type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(dbaas_registration_databases_postgresql_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Postgresql"
      },
      {
       "expr": "avg(dbaas_registration_databases_mongodb_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Mongodb"
      },
      {
       "expr": "avg(dbaas_registration_databases_cassandra_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) ",
       "legendFormat": "Cassandra"
      },
      {
       "expr": "avg(dbaas_registration_databases_opensearch_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "OpenSearch"
      },
      {
       "expr": "avg(dbaas_registration_databases_redis_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "Redis"
      }
     ]
    },
    {
     "title": "Registry discrepancy count over time",
     "type": "timeseries",
     "description": "Shows the number of databases that are registered in DBaaS but absent from adapter database lists.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))",
       "legendFormat": "lost databases"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage: $jvm_heap_part",
     "type": "timeseries",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "repeat": "jvm_heap_part",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "allocated"
      }
     ]
    },
    {
     "title": "Heap Usage: $jvm_heap_part",
     "type": "timeseries",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "allocated"
      }
     ]
    },
    {
     "title": "Heap Usage: $jvm_heap_part",
     "type": "timeseries",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"$jvm_heap_part\"})",
       "legendFormat": "allocated"
      }
     ]
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non Heap: $jvm_nonheap_part",
     "type": "timeseries",
     "description": "The amount of used memory in non heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "repeat": "jvm_nonheap_part",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "legendFormat": "allocated"
      }
     ]
    },
    {
     "title": "Non Heap: $jvm_nonheap_part",
     "type": "timeseries",
     "description": "The amount of used memory in non heap area multiplied by different ids",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "avg(jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"$jvm_nonheap_part\"})",
       "legendFormat": "allocated"
      }
     ]
    },
    {
     "title": "Byte buffers: $jvm_buffers_type",
     "type": "timeseries",
     "description": "An estimate of the total capacity of the buffers in this pool (Off-heap buffers from allocateDirect())",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "repeat": "jvm_buffers_type",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_buffer_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_buffer_total_capacity_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Byte buffers: $jvm_buffers_type",
     "type": "timeseries",
     "description": "An estimate of the total capacity of the buffers in this pool (Off-heap buffers from allocateDirect())",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(jvm_buffer_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "legendFormat": "used"
      },
      {
       "expr": "avg(jvm_buffer_total_capacity_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"$jvm_buffers_type\"})",
       "legendFormat": "capacity"
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC: Pauses",
     "type": "timeseries",
     "description": "Time spent for minor and major GC per second",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(rate(jvm_gc_pause_seconds_sum{container=\"$service_name\", namespace=\"$namespace\"}[$inter])) by (cause, action)",
       "legendFormat": "{{cause}}: {{action}}"
      }
     ]
    },
    {
     "title": "GC: Allocations",
     "type": "timeseries",
     "description": "Increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(rate(jvm_gc_memory_allocated_bytes_total{container=\"$service_name\", namespace=\"$namespace\"}[$inter]))",
       "legendFormat": "Allocations"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(jvm_threads_live_threads{container=\"$service_name\", namespace=\"$namespace\"})",
       "legendFormat": "current"
      },
      {
       "expr": "avg(jvm_threads_daemon_threads{container=\"$service_name\", namespace=\"$namespace\"})",
       "legendFormat": "daemon"
      },
      {
       "expr": "avg(jvm_threads_peak_threads{container=\"$service_name\", namespace=\"$namespace\"})",
       "legendFormat": "peak"
      }
     ]
    },
    {
     "title": "Threads: State",
     "type": "timeseries",
     "description": "Shows information about Java threads",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(jvm_threads_states_threads{container=\"$service_name\", namespace=\"$namespace\"}) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  { "title": "JDBC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Number Of Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "agroal_active_count{container=\"$service_name\", namespace=\"$namespace\"}",
     "legendFormat": "datasource: {{datasource}} - pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Number Of Idle Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "agroal_available_count{container=\"$service_name\", namespace=\"$namespace\"}",
     "legendFormat": "datasource: {{datasource}} - pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Number Of Threads Waiting Connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "agroal_awaiting_count{container=\"$service_name\", namespace=\"$namespace\"}",
     "legendFormat": "datasource: {{datasource}} - pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Number Of Leaks Detected",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "agroal_leak_detection_count_total{container=\"$service_name\", namespace=\"$namespace\"}",
     "legendFormat": "datasource: {{datasource}}"
    }
   ]
  },
  {
   "title": "Application Average Wait Connection Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "agroal_blocking_time_average_milliseconds{container=\"$service_name\", namespace=\"$namespace\"}",
     "legendFormat": "datasource: {{datasource}} - pod: {{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP 2xx Responses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"2..\"}[$inter])) by (uri)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Timings. Code 2xx",
     "type": "timeseries",
     "description": "Shows maximum time of requests execution to service endpoints",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(increase(http_server_requests_seconds_max{container=\"$service_name\", namespace=\"$namespace\"}[$inter])) by (uri) OR on() vector(0)",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Statistics. Code: 4xx",
     "type": "timeseries",
     "description": "Shows amount of requests to different URLs per second with code 4xx",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"4..\"}[$inter])) by (uri) OR on() vector(0)",
       "legendFormat": "{{uri}}"
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 5xx",
     "type": "timeseries",
     "description": "Shows amount of requests to different URLs per second with code 5xx",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"5..\"}[$inter])) by (uri) OR on() vector(0)",
       "legendFormat": "{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Registered databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "All registered databases",
     "type": "stat",
     "description": "Total number of databases registered in DBaaS.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))"
      }
     ]
    },
    {
     "title": "PostgreSQL registered databases",
     "type": "stat",
     "description": "Number of PostgreSQL databases registered in DBaaS.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_postgresql_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) + max(dbaas_registration_databases_postgresql_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))"
      }
     ]
    },
    {
     "title": "MongoDB registered databases",
     "type": "stat",
     "description": "Number of MongoDB databases registered in DBaaS.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_mongodb_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) + max(dbaas_registration_databases_mongodb_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))"
      }
     ]
    },
    {
     "title": "Cassandra registered databases",
     "type": "stat",
     "description": "Number of Cassandra databases registered in DBaaS.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_cassandra_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) + max(dbaas_registration_databases_cassandra_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))"
      }
     ]
    },
    {
     "title": "OpenSearch registered databases",
     "type": "stat",
     "description": "Number of OpenSearch databases registered in DBaaS.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_opensearch_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) + max(dbaas_registration_databases_opensearch_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))"
      }
     ]
    },
    {
     "title": "Redis registered databases",
     "type": "stat",
     "description": "Number of Redis databases registered in DBaaS.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(dbaas_registration_databases_redis_total_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0)) + max(dbaas_registration_databases_redis_lost_number{container=\"$service_name\", namespace=\"$namespace\"} OR on() vector(0))"
      }
     ]
    }
   ]
  }
 ]
}