# ============== DEPLOYMENT VARIABLES ============================
APPLICATION_NAME: dbaas
SERVICE_NAME: dbaas-operator
DBAAS_RECREATE_DEPLOYMENT_STRATEGY: false
NODE_SELECTOR_DBAAS_KEY: region
REGION_DBAAS: database
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: true
MANAGED_BY: saasDeployer
LIVENESS_PROBE_INITIAL_DELAY_SECONDS: 15

# ============== SERVICE VARIABLES ============================
DBAAS_SECURITY_CONFIGURATION_LOCATION: '/etc/dbaas/security'
DBAAS_AGGREGATOR_USERNAME: cluster-dba
HEALTH_PROBE_BIND_ADDRESS: 8081
METRICS_BIND_ADDRESS: 0
WATCH_NAMESPACE: namespace
CPU_REQUEST: "100m"
MEMORY_LIMIT: "520Mi"
CPU_LIMIT: "2"
REPLICAS: 1
