# ============== DEPLOYMENT VARIABLES ============================
SERVICE_NAME: dbaas-operator
NODE_SELECTOR_DBAAS_KEY: region
REGION_DBAAS: database
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: true
MANAGED_BY: saasDeployer
LIVENESS_PROBE_INITIAL_DELAY_SECONDS: 15
IMAGE_REPOSITORY: ghcr.io/netcracker/qubership-dbaas-operator
TAG: feat-dbaas-operator-snapshot
NAMESPACE: default
PAAS_PLATFORM: KUBERNETES
PAAS_VERSION: '1.25'
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
INSTALL_DBAAS_OPERATOR: true
RESTRICTED_ENVIRONMENT: false

# ============== SERVICE VARIABLES ============================
WATCH_NAMESPACES: ''
LOG_LEVEL: "info"

# ============== Resources ============================
CPU_REQUEST: "10m"
CPU_LIMIT: "500m"
MEMORY_REQUEST: "64Mi"
MEMORY_LIMIT: "128Mi"
REPLICAS: 1
HPA_ENABLED: false
HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT: 75

# ============== Topology ============================
CLOUD_TOPOLOGY_KEY: "kubernetes.io/hostname"
