#!/usr/bin/env python3
"""Convert legacy DBaaS declarations to dedicated dbaas-operator CRDs.

The converter is intentionally conservative. It supports common legacy JSON
inputs with the Python standard library. If PyYAML is installed, it also reads
legacy YAML and uses PyYAML for output formatting.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    yaml = None


RESERVED_CLASSIFIER_KEYS = {
    "microserviceName",
    "scope",
    "namespace",
    "tenantId",
    "customKeys",
}
DATABASE_DECLARATION_FIELDS = {
    "classifierConfig",
    "type",
    "lazy",
    "settings",
    "namePrefix",
    "physicalDatabaseId",
    "versioningConfig",
    "initialInstantiation",
}
DB_POLICY_FIELDS = {
    "apiVersion",
    "kind",
    "metadata",
    "microserviceName",
    "services",
    "policy",
    "disableGlobalPermissions",
}

# labels and annotations are ordinary metadata every Kubernetes resource
# supports -- the generated CR carries them forward verbatim (see
# target_metadata()) rather than dropping them, so they belong here, not in
# SILENTLY_DROPPED_METADATA_FIELDS.
PRESERVED_METADATA_FIELDS = {"name", "namespace", "labels", "annotations"}
# These fields are genuinely regenerated by the API server for a brand-new resource --
# they describe the *old* object's identity/history in etcd, not anything a client ever
# sets, so they have no meaning to carry over and are safe to drop without blocking.
# ownerReferences and finalizers do NOT belong here: Kubernetes does not automatically
# recreate arbitrary owner references or finalizers on a differently-named/differently-
# kinded replacement resource -- an owner relationship or a delete-time hook the old
# object depended on would silently stop existing. Anything dropped that is not in this
# set still blocks -- it is a field this converter does not recognize at all, not a
# known-and-intentionally-unmapped one.
SILENTLY_DROPPED_METADATA_FIELDS = {
    "creationTimestamp",
    "resourceVersion",
    "uid",
    "generation",
    "managedFields",
    "selfLink",
}
# The Core Operator's `kind: DBaaS` wrapper stamps these two labels onto every
# wrapped resource itself, not onto the declaration/policy the wrapper
# carries -- they describe the wrapper's own processing state (has the Core
# Operator already handled this object; may its cleanup delete it) and have
# no meaning once the wrapper is gone and the declaration is a native,
# unwrapped dbaas-operator CR. Ordinary application labels, Argo CD/tracking
# labels, and annotations are not wrapper-only and are never filtered here.
# A label with one of these exact names on a *direct* (non-`kind: DBaaS`)
# DbPolicy/DatabaseDeclaration is a real, unrelated label and is preserved --
# only the wrapper's own metadata.labels are filtered (see is_wrapper in
# target_metadata()).
WRAPPER_ONLY_LABELS = {
    "app.kubernetes.io/processed-by-operator",
    "deployer.cleanup/allow",
}


class TemplatedNameRequired(Exception):
    """A default resource name is templated, or mixes literal text with a Helm
    expression, and no explicit override was supplied.

    Slugging the template source text into one fixed literal would collide
    across every release of the same chart; the caller must supply an
    explicit, release-specific ``override_name`` instead (see
    ``resource_name``).
    """

    def __init__(self, hint: str) -> None:
        super().__init__(f"templated identity requires an explicit target name: {hint!r}")
        self.hint = hint


def is_templated(value: Any) -> bool:
    return isinstance(value, str) and "{{" in value


def is_whole_template(value: str) -> bool:
    """Whether ``value`` is entirely one ``{{ ... }}`` Helm expression, as opposed
    to literal text mixed with one. Only a whole-template value's rendered
    result is the deployer's responsibility to keep DNS-1123-safe; a mixed
    value cannot be checked at all and must never be produced automatically."""

    # A greedy ``{{.*}}`` also accepts two expressions with literal text
    # between them.  A whole template is exactly one delimiter pair.
    return re.fullmatch(r"\{\{(?:(?!\{\{|\}\}).)*\}\}", value.strip(), re.S) is not None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Legacy JSON/YAML file")
    parser.add_argument("--output", required=True, help="Output YAML file")
    parser.add_argument("--service-name")
    parser.add_argument("--namespace", default="{{ .Values.NAMESPACE }}")
    parser.add_argument(
        "--operator-namespace",
        required=True,
        help="Namespace of the dbaas-operator instance that will manage the generated resources",
    )
    parser.add_argument("--name-prefix", default="")
    args = parser.parse_args()
    # argparse's required=True still accepts an empty string. spec.operatorNamespace is
    # required and MinLength=1 in the CRDs, so an empty value would emit a CR the API
    # server rejects; fail here with a clear message instead.
    if not args.operator_namespace.strip():
        parser.error("--operator-namespace must not be empty")
    args.service_name_explicit = args.service_name is not None
    args.service_name = args.service_name or "{{ .Values.SERVICE_NAME }}"

    source = Path(args.input)
    warnings: list[str] = []
    errors: list[str] = []
    docs = load_documents(source, warnings)
    resources: list[dict[str, Any]] = []

    try:
        for doc_index, doc in enumerate(docs, start=1):
            if doc is None:
                continue
            if isinstance(doc, list):
                for item_index, item in enumerate(doc, start=1):
                    if not isinstance(item, dict):
                        errors.append(f"Document {doc_index}: item #{item_index} must be an object")
            for item_index, item in enumerate(as_legacy_items(doc), start=1):
                resources.extend(convert_item(item, doc_index, item_index, args, warnings, errors))
    except TemplatedNameRequired as exc:
        raise SystemExit(
            f"{exc}. This CLI has no per-item name override; either give the source resource a "
            "concrete metadata.name, or migrate it through the package writer (apply_migration.py) "
            "with an explicit, release-specific plan name instead."
        ) from None

    if not resources:
        raise SystemExit("No supported DBaaS declarations found")

    reject_duplicate_resources(resources, errors)
    for resource in resources:
        validate_target_resource(resource, errors)
    for warning in warnings:
        print(f"WARNING: {warning}", file=sys.stderr)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(
            f"Conversion failed with {len(errors)} error(s); the output file was not written"
        )
    Path(args.output).write_text(dump_yaml_documents(resources), encoding="utf-8")
    print(f"Wrote {len(resources)} resource(s) to {args.output}", file=sys.stderr)
    return 0


def reject_json_constant(value: str) -> Any:
    raise ValueError(f"numeric constant {value!r} is not valid JSON")


def load_documents(path: Path, warnings: list[str]) -> list[Any]:
    text = path.read_text(encoding="utf-8-sig")
    suffix = path.suffix.lower()
    if suffix == ".json":
        try:
            data = json.loads(text, parse_constant=reject_json_constant)
        except ValueError as exc:
            raise SystemExit(f"{path}: invalid JSON: {exc}") from None
        return data if isinstance(data, list) else [data]
    if yaml is None:
        raise SystemExit("YAML input requires PyYAML. Install PyYAML or convert the source to JSON first.")
    try:
        return list(yaml.safe_load_all(text))
    except yaml.YAMLError:
        warnings.append(
            "YAML required Helm-template sanitization; standalone template actions were commented and "
            "conditional semantics must be reviewed manually"
        )
        return list(yaml.safe_load_all(sanitize_helm_yaml(text)))


def sanitize_helm_yaml(text: str) -> str:
    """Make common Helm-template YAML parseable enough for migration.

    Comment standalone template actions and quote scalar template expressions.
    This makes common chart declarations parseable, but can remove conditional
    semantics; load_documents emits a warning whenever this fallback is used.
    """

    sanitized: list[str] = []
    scalar_with_template = re.compile(r"^(\s*[^#\n][^:]*:\s*)(.*\{\{.*\}\}.*)$")
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("{{") and ":" not in stripped:
            sanitized.append(f"{line[: len(line) - len(line.lstrip())]}# {stripped}")
            continue
        match = scalar_with_template.match(line)
        if match:
            prefix, value = match.groups()
            bare_value = value.strip()
            if not (bare_value.startswith("'") and bare_value.endswith("'")):
                escaped = bare_value.strip('"').replace("'", "''")
                sanitized.append(f"{prefix}'{escaped}'")
                continue
        sanitized.append(line)
    return "\n".join(sanitized) + "\n"


def as_legacy_items(doc: Any) -> list[dict[str, Any]]:
    if isinstance(doc, list):
        return [item for item in doc if isinstance(item, dict)]
    if isinstance(doc, dict):
        return [doc]
    return []


def convert_item(
    item: dict[str, Any],
    doc_index: int,
    item_index: int,
    args: argparse.Namespace,
    warnings: list[str],
    errors: list[str],
) -> list[dict[str, Any]]:
    kind = str(item.get("kind", ""))
    sub_kind = str(item.get("subKind", ""))
    legacy_kind = sub_kind or kind
    legacy_kind_lower = legacy_kind.lower()

    body_value = item.get("spec") if kind == "DBaaS" else item
    metadata_value = item.get("metadata")
    if not isinstance(body_value, dict):
        errors.append(f"Document {doc_index}: spec must be an object")
        return []
    if metadata_value is not None and not isinstance(metadata_value, dict):
        errors.append(f"Document {doc_index}: metadata must be an object")
        return []
    is_wrapper = kind == "DBaaS"
    if is_wrapper:
        body = dict(body_value)
        metadata = dict(metadata_value or {})
    else:
        body = dict(item)
        metadata = dict(metadata_value or {})

    reject_dropped_metadata(metadata, f"Document {doc_index}", errors)

    if legacy_kind_lower == "databasedeclaration":
        declarations = body.get("declarations")
        if declarations is None:
            # No declarations[] wrapper: the document itself is the one
            # declaration, but it still carries envelope fields (apiVersion,
            # kind, metadata) that DATABASE_DECLARATION_FIELDS was never
            # meant to validate -- those belong to the document, not the
            # declaration body, and would otherwise be rejected as unknown.
            declarations = [
                {k: v for k, v in body.items() if k not in ("apiVersion", "kind", "subKind", "metadata")}
            ]
        if not isinstance(declarations, list):
            warnings.append(f"Document {doc_index}: DatabaseDeclaration.declarations is not a list")
            return []
        resources = []
        for declaration_index, declaration in enumerate(declarations, start=1):
            if not isinstance(declaration, dict):
                warnings.append(f"Document {doc_index}: skipped non-object declaration #{declaration_index}")
                continue
            resources.append(
                convert_database_declaration(
                    declaration,
                    metadata,
                    doc_index,
                    declaration_index,
                    len(declarations) > 1,
                    args,
                    warnings,
                    errors,
                    is_wrapper=is_wrapper,
                )
            )
        return resources

    if legacy_kind_lower == "dbpolicy":
        return [
            convert_db_policy(
                body, metadata, doc_index, item_index, args, warnings, errors, is_wrapper=is_wrapper
            )
        ]

    warnings.append(f"Document {doc_index}: skipped unsupported kind/subKind {legacy_kind!r}")
    return []


def convert_database_declaration(
    declaration: dict[str, Any],
    old_metadata: dict[str, Any],
    doc_index: int,
    declaration_index: int,
    multiple_declarations: bool,
    args: argparse.Namespace,
    warnings: list[str],
    errors: list[str],
    override_name: str | None = None,
    is_wrapper: bool = False,
) -> dict[str, Any]:
    reject_unknown_fields(
        declaration,
        DATABASE_DECLARATION_FIELDS,
        f"DatabaseDeclaration #{declaration_index}",
        errors,
    )
    classifier_config = declaration.get("classifierConfig") or {}
    classifier = classifier_config.get("classifier") if isinstance(classifier_config, dict) else None
    if not isinstance(classifier, dict):
        classifier = {}
        errors.append(f"DatabaseDeclaration #{declaration_index}: missing classifierConfig.classifier")
    default_name = database_name_hint(declaration, classifier, doc_index, declaration_index)
    metadata = target_metadata(
        old_metadata,
        args,
        default_name,
        doc_index,
        declaration_index,
        errors,
        disambiguate_parent=multiple_declarations,
        override_name=override_name,
        is_wrapper=is_wrapper,
    )
    target_classifier = convert_classifier(
        classifier, args.service_name, errors, f"DatabaseDeclaration #{declaration_index} classifier"
    )
    legacy_namespace = target_classifier.pop("namespace", None)
    if legacy_namespace not in (None, "", metadata["namespace"]):
        # A warning here does not stop --apply from deleting the source: the operator always
        # derives the classifier namespace from metadata.namespace, so a pin to a different
        # namespace can never be honored, and silently dropping it would leave the runtime
        # client still expecting the pinned namespace once the source is gone. Block instead.
        errors.append(
            f"InternalDatabase {metadata['name']} classifier.namespace {legacy_namespace!r} differs from "
            f"metadata.namespace {metadata['namespace']!r}; the operator always derives the classifier "
            "namespace from metadata.namespace, so this pin cannot be migrated"
        )

    spec: dict[str, Any] = {
        "operatorNamespace": args.operator_namespace,
        "classifier": target_classifier,
    }

    for field in ("type", "namePrefix", "physicalDatabaseId", "versioningConfig", "initialInstantiation"):
        if field in declaration:
            spec[field] = convert_nested_classifiers(
                declaration[field], args.service_name, errors, f"DatabaseDeclaration #{declaration_index}.{field}"
            )
    # spec.type and spec.namePrefix are plain string fields on the target CRD. The presence
    # checks below (`if not spec.get("type")`) only catch a falsy value -- a truthy
    # non-string (a numeric type, a non-empty list-valued namePrefix) would pass straight
    # through into the generated CR and only be rejected by the API server at apply time.
    for field in ("type", "namePrefix"):
        if field in declaration and not isinstance(declaration[field], str):
            errors.append(
                f"DatabaseDeclaration #{declaration_index}.{field} must be a string, "
                f"got {type(declaration[field]).__name__}"
            )

    if "lazy" in declaration:
        coerced = coerce_bool(declaration["lazy"])
        if not isinstance(coerced, bool):
            errors.append(
                f"InternalDatabase {metadata['name']} has non-boolean lazy {declaration['lazy']!r}; "
                "use true or false"
            )
        else:
            spec["lazy"] = coerced

    if "settings" in declaration:
        settings = declaration["settings"]
        spec["settings"] = settings
        if not isinstance(settings, dict):
            errors.append(
                f"InternalDatabase {metadata['name']} has invalid settings at settings: expected an object"
            )
        else:
            for path, reason in json_value_errors(settings, "settings"):
                errors.append(
                    f"InternalDatabase {metadata['name']} has invalid JSON value at {path}: {reason}"
                )

    target_classifier = spec["classifier"]
    for required_key in ("microserviceName", "scope"):
        if not target_classifier.get(required_key):
            warnings.append(f"InternalDatabase {default_name} is missing classifier.{required_key}")
    if not spec.get("type"):
        warnings.append(f"InternalDatabase {default_name} is missing type")

    if spec.get("lazy") is True:
        initial = spec.get("initialInstantiation")
        if isinstance(initial, dict) and initial.get("approach") == "clone":
            # A warning here does not stop --apply from deleting the source:
            # this combination is not "worth a second look", it is invalid
            # by the converter's own judgment, so it blocks.
            errors.append("lazy=true with initialInstantiation.approach=clone is invalid")
    initial = spec.get("initialInstantiation")
    if isinstance(initial, dict) and initial.get("approach") == "clone" and "sourceClassifier" not in initial:
        # A warning here does not stop --apply from deleting the source: without a
        # sourceClassifier the operator has nothing to clone from, so this is invalid by the
        # converter's own judgment, not merely worth a second look.
        errors.append("initialInstantiation.approach=clone requires sourceClassifier")
    validate_source_classifier_owner(spec, default_name, warnings, errors)

    return {
        "apiVersion": "dbaas.netcracker.com/v1",
        "kind": "InternalDatabase",
        "metadata": metadata,
        "spec": spec,
    }


def json_value_errors(value: Any, path: str) -> list[tuple[str, str]]:
    if value is None or isinstance(value, (str, bool, int)):
        return []
    if isinstance(value, float):
        return [] if math.isfinite(value) else [(path, "non-finite numbers are not valid JSON")]
    if isinstance(value, list):
        errors: list[tuple[str, str]] = []
        for index, item in enumerate(value):
            errors.extend(json_value_errors(item, f"{path}[{index}]"))
        return errors
    if isinstance(value, dict):
        errors = []
        for key, item in value.items():
            if not isinstance(key, str):
                errors.append((f"{path}[{key!r}]", "object keys must be strings"))
                continue
            errors.extend(json_value_errors(item, json_child_path(path, key)))
        return errors
    return [(path, f"{type(value).__name__} values are not valid JSON")]


def json_child_path(path: str, key: str) -> str:
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", key):
        return f"{path}.{key}"
    return f"{path}[{json.dumps(key, ensure_ascii=False)}]"


_DNS_LABEL = re.compile(r"[a-z0-9](?:[-a-z0-9]*[a-z0-9])?")
_DNS_SUBDOMAIN = re.compile(
    r"[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9](?:[-a-z0-9]*[a-z0-9])?)*"
)
_NAME_PART = re.compile(r"[A-Za-z0-9](?:[-_.A-Za-z0-9]*[A-Za-z0-9])?")
_LABEL_VALUE = re.compile(r"[A-Za-z0-9](?:[-_.A-Za-z0-9]*[A-Za-z0-9])?")


def _qualified_name(value: str) -> bool:
    prefix, slash, name = value.rpartition("/")
    if not slash:
        name, prefix = value, ""
    return (
        1 <= len(name) <= 63
        and _NAME_PART.fullmatch(name) is not None
        and (not prefix or (len(prefix) <= 253 and _DNS_SUBDOMAIN.fullmatch(prefix) is not None))
    )


def _string_field(
    mapping: dict[str, Any], key: str, context: str, errors: list[str], *, required: bool = False
) -> None:
    value = mapping.get(key)
    if value is None:
        if required:
            errors.append(f"{context}.{key} is required")
        return
    if not isinstance(value, str) or (required and not value):
        errors.append(f"{context}.{key} must be a non-empty string" if required else f"{context}.{key} must be a string")


def _object(value: Any, context: str, errors: list[str]) -> dict[str, Any] | None:
    if not isinstance(value, dict):
        errors.append(f"{context} must be an object")
        return None
    return value


def _known_fields(value: dict[str, Any], allowed: set[str], context: str, errors: list[str]) -> None:
    unknown = sorted(set(value) - allowed)
    if unknown:
        errors.append(f"{context} has unsupported fields: {', '.join(unknown)}")


def _validate_classifier(value: Any, context: str, errors: list[str], *, required: bool) -> None:
    classifier = _object(value, context, errors)
    if classifier is None:
        return
    _string_field(classifier, "microserviceName", context, errors, required=required)
    _string_field(classifier, "scope", context, errors, required=required)
    _string_field(classifier, "namespace", context, errors)
    _string_field(classifier, "tenantId", context, errors)
    scope = classifier.get("scope")
    if isinstance(scope, str) and "{{" not in scope and scope not in ("service", "tenant"):
        errors.append(f"{context}.scope must be 'service' or 'tenant'")
    for key in ("customKeys", "extraKeys"):
        nested = classifier.get(key)
        if nested is None:
            continue
        if not isinstance(nested, dict):
            errors.append(f"{context}.{key} must be an object")
            continue
        for path, reason in json_value_errors(nested, f"{context}.{key}"):
            errors.append(f"{path}: {reason}")


def _validate_metadata(metadata: Any, errors: list[str]) -> None:
    value = _object(metadata, "metadata", errors)
    if value is None:
        return
    name = value.get("name")
    if not isinstance(name, str) or not name:
        errors.append("metadata.name is required and must be a string")
    elif "{{" not in name and (len(name) > 63 or _DNS_LABEL.fullmatch(name) is None):
        errors.append(f"metadata.name {name!r} is not a valid DNS-1123 label")
    namespace = value.get("namespace")
    if namespace is not None:
        if not isinstance(namespace, str):
            errors.append("metadata.namespace must be a string")
        elif "{{" not in namespace and (len(namespace) > 63 or _DNS_LABEL.fullmatch(namespace) is None):
            errors.append(f"metadata.namespace {namespace!r} is not a valid RFC-1123 namespace label")
    for field in ("labels", "annotations"):
        entries = value.get(field)
        if entries is None:
            continue
        if not isinstance(entries, dict):
            errors.append(f"metadata.{field} must be an object")
            continue
        for key, item in entries.items():
            if not isinstance(key, str) or ("{{" not in key and not _qualified_name(key)):
                errors.append(f"metadata.{field} key {key!r} is not a valid qualified name")
            if not isinstance(item, str):
                errors.append(f"metadata.{field}[{key!r}] must be a string")
            elif field == "labels" and "{{" not in item and (
                len(item) > 63 or (item and _LABEL_VALUE.fullmatch(item) is None)
            ):
                errors.append(f"metadata.labels[{key!r}] is not a valid label value")


def _validate_internal_database(spec: dict[str, Any], errors: list[str]) -> None:
    _known_fields(
        spec,
        {
            "operatorNamespace", "classifier", "type", "lazy", "settings", "namePrefix",
            "physicalDatabaseId", "initialInstantiation", "versioningConfig",
        },
        "spec",
        errors,
    )
    _string_field(spec, "operatorNamespace", "spec", errors, required=True)
    operator_namespace = spec.get("operatorNamespace")
    if isinstance(operator_namespace, str) and "{{" not in operator_namespace and (
        len(operator_namespace) > 63 or _DNS_LABEL.fullmatch(operator_namespace) is None
    ):
        errors.append(f"spec.operatorNamespace {operator_namespace!r} is not a valid RFC-1123 namespace label")
    _string_field(spec, "type", "spec", errors, required=True)
    for key in ("namePrefix", "physicalDatabaseId"):
        _string_field(spec, key, "spec", errors)
    if "lazy" in spec and not isinstance(spec["lazy"], bool):
        errors.append("spec.lazy must be a boolean")
    settings = spec.get("settings")
    if settings is not None:
        if not isinstance(settings, dict):
            errors.append("spec.settings must be an object")
        else:
            for path, reason in json_value_errors(settings, "spec.settings"):
                errors.append(f"{path}: {reason}")
    _validate_classifier(spec.get("classifier"), "spec.classifier", errors, required=True)

    initial = spec.get("initialInstantiation")
    if initial is not None:
        initial = _object(initial, "spec.initialInstantiation", errors)
        if initial is not None:
            _known_fields(initial, {"approach", "sourceClassifier"}, "spec.initialInstantiation", errors)
            _string_field(initial, "approach", "spec.initialInstantiation", errors)
            source = initial.get("sourceClassifier")
            if initial.get("approach") == "clone" and source is None:
                errors.append("spec.initialInstantiation.sourceClassifier is required for clone")
            if source is not None:
                _validate_classifier(source, "spec.initialInstantiation.sourceClassifier", errors, required=True)

    versioning = spec.get("versioningConfig")
    if versioning is not None:
        versioning = _object(versioning, "spec.versioningConfig", errors)
        if versioning is not None:
            _known_fields(versioning, {"approach"}, "spec.versioningConfig", errors)
            _string_field(versioning, "approach", "spec.versioningConfig", errors)


def _validate_string_list(value: Any, context: str, errors: list[str], *, non_empty: bool = False) -> None:
    if not isinstance(value, list) or (non_empty and not value) or not all(isinstance(item, str) for item in value):
        errors.append(f"{context} must be {'a non-empty ' if non_empty else 'a '}list of strings")


def _validate_access_policy(spec: dict[str, Any], errors: list[str]) -> None:
    _known_fields(
        spec,
        {"operatorNamespace", "microserviceName", "services", "policy", "disableGlobalPermissions"},
        "spec",
        errors,
    )
    _string_field(spec, "operatorNamespace", "spec", errors, required=True)
    operator_namespace = spec.get("operatorNamespace")
    if isinstance(operator_namespace, str) and "{{" not in operator_namespace and (
        len(operator_namespace) > 63 or _DNS_LABEL.fullmatch(operator_namespace) is None
    ):
        errors.append(f"spec.operatorNamespace {operator_namespace!r} is not a valid RFC-1123 namespace label")
    _string_field(spec, "microserviceName", "spec", errors, required=True)
    if "disableGlobalPermissions" in spec and not isinstance(spec["disableGlobalPermissions"], bool):
        errors.append("spec.disableGlobalPermissions must be a boolean")
    services = spec.get("services")
    policy = spec.get("policy")
    if not services and not policy and "disableGlobalPermissions" not in spec:
        errors.append(
            "spec.services or spec.policy must be non-empty, or spec.disableGlobalPermissions must be present"
        )
    if services is not None:
        if not isinstance(services, list):
            errors.append("spec.services must be an array")
        else:
            for index, item in enumerate(services):
                entry = _object(item, f"spec.services[{index}]", errors)
                if entry is None:
                    continue
                _known_fields(entry, {"name", "roles"}, f"spec.services[{index}]", errors)
                _string_field(entry, "name", f"spec.services[{index}]", errors, required=True)
                _validate_string_list(entry.get("roles"), f"spec.services[{index}].roles", errors, non_empty=True)
    if policy is not None:
        if not isinstance(policy, list):
            errors.append("spec.policy must be an array")
        else:
            for index, item in enumerate(policy):
                entry = _object(item, f"spec.policy[{index}]", errors)
                if entry is None:
                    continue
                _known_fields(entry, {"type", "defaultRole", "additionalRole"}, f"spec.policy[{index}]", errors)
                _string_field(entry, "type", f"spec.policy[{index}]", errors, required=True)
                _string_field(entry, "defaultRole", f"spec.policy[{index}]", errors, required=True)
                if "additionalRole" in entry:
                    _validate_string_list(entry["additionalRole"], f"spec.policy[{index}].additionalRole", errors)


def validate_target_resource(resource: dict[str, Any], errors: list[str]) -> None:
    """Validate the generated object once against the target CRD shapes."""

    if resource.get("apiVersion") != "dbaas.netcracker.com/v1":
        errors.append("apiVersion must be dbaas.netcracker.com/v1")
    if resource.get("kind") not in ("InternalDatabase", "DatabaseAccessPolicy"):
        errors.append(f"unsupported generated kind {resource.get('kind')!r}")
    _validate_metadata(resource.get("metadata"), errors)
    spec = _object(resource.get("spec"), "spec", errors)
    if spec is None:
        return
    kind = resource.get("kind")
    if kind == "InternalDatabase":
        _validate_internal_database(spec, errors)
    elif kind == "DatabaseAccessPolicy":
        _validate_access_policy(spec, errors)


def validate_source_classifier_owner(
    spec: dict[str, Any],
    resource_name_hint: str,
    warnings: list[str],
    errors: list[str],
) -> None:
    initial = spec.get("initialInstantiation")
    if not isinstance(initial, dict):
        return
    source_classifier = initial.get("sourceClassifier")
    if not isinstance(source_classifier, dict):
        return

    target_classifier = spec.get("classifier")
    if not isinstance(target_classifier, dict):
        return
    target_owner = target_classifier.get("microserviceName")
    source_owner = source_classifier.get("microserviceName")
    if not source_owner and target_owner:
        source_classifier["microserviceName"] = target_owner
        warnings.append(
            f"InternalDatabase {resource_name_hint} sourceClassifier.microserviceName was missing; "
            "filled it from classifier.microserviceName"
        )
    elif target_owner and source_owner != target_owner:
        # A warning here does not stop --apply from deleting the source:
        # this is invalid by the converter's own judgment ("cross-service
        # clones are invalid"), so it blocks rather than shipping a CR that
        # clones across microservices.
        errors.append(
            f"InternalDatabase {resource_name_hint} sourceClassifier.microserviceName must match "
            "classifier.microserviceName; cross-service clones are invalid"
        )


def database_name_hint(
    declaration: dict[str, Any],
    classifier: dict[str, Any],
    doc_index: int,
    declaration_index: int,
) -> str:
    scope = str(classifier.get("scope") or "db")
    custom_keys = classifier.get("customKeys")
    logical_name = None
    if isinstance(custom_keys, dict):
        logical_name = (
            custom_keys.get("logicalDbName")
            or custom_keys.get("logicalDBName")
            or custom_keys.get("logicalDBname")
        )
    if logical_name:
        return f"{scope}-{logical_name}-db"
    if classifier.get("transactional") is True:
        return f"{scope}-transactional-db"
    db_type = declaration.get("type")
    if db_type:
        return f"{scope}-{db_type}-db"
    return f"internaldatabase-{doc_index}-{declaration_index}"


def convert_db_policy(
    body: dict[str, Any],
    old_metadata: dict[str, Any],
    doc_index: int,
    item_index: int,
    args: argparse.Namespace,
    warnings: list[str],
    errors: list[str],
    override_name: str | None = None,
    is_wrapper: bool = False,
) -> dict[str, Any]:
    reject_unknown_fields(body, DB_POLICY_FIELDS, "DatabaseAccessPolicy", errors)
    source_microservice_name = body.get("microserviceName") or label_value(
        old_metadata, "app.kubernetes.io/instance"
    )
    if getattr(args, "service_name_explicit", False):
        microservice_name = args.service_name
    else:
        microservice_name = source_microservice_name or args.service_name
    if not source_microservice_name and not getattr(args, "service_name_explicit", False):
        warnings.append(
            "DatabaseAccessPolicy.spec.microserviceName uses the --service-name fallback; "
            "verify it against the owning service"
        )
    if not microservice_name:
        errors.append("DatabaseAccessPolicy.spec.microserviceName could not be derived")
        microservice_name = "TODO-service-name"

    spec: dict[str, Any] = {
        "operatorNamespace": args.operator_namespace,
        "microserviceName": normalize_service_template(str(microservice_name), args.service_name),
    }
    for field in ("services", "policy"):
        if field in body:
            spec[field] = body[field]
    if "disableGlobalPermissions" in body:
        coerced = coerce_bool(body["disableGlobalPermissions"])
        if not isinstance(coerced, bool):
            errors.append(
                f"DatabaseAccessPolicy.spec.disableGlobalPermissions {body['disableGlobalPermissions']!r} "
                "is not a boolean"
            )
        else:
            spec["disableGlobalPermissions"] = coerced

    if not spec.get("services") and not spec.get("policy") and "disableGlobalPermissions" not in spec:
        errors.append(
            "DatabaseAccessPolicy must have a non-empty services or policy list, or disableGlobalPermissions present"
        )

    return {
        "apiVersion": "dbaas.netcracker.com/v1",
        "kind": "DatabaseAccessPolicy",
        "metadata": target_metadata(
            old_metadata,
            args,
            "database-access-policy",
            doc_index,
            item_index,
            errors,
            override_name=override_name,
            is_wrapper=is_wrapper,
        ),
        "spec": spec,
    }


def convert_nested_classifiers(value: Any, service_name: str, errors: list[str], context: str) -> Any:
    if isinstance(value, dict):
        converted = {}
        for key, nested in value.items():
            if key == "sourceClassifier" and isinstance(nested, dict):
                converted[key] = convert_classifier(nested, service_name, errors, f"{context}.sourceClassifier")
            else:
                converted[key] = convert_nested_classifiers(nested, service_name, errors, context)
        return converted
    if isinstance(value, list):
        return [convert_nested_classifiers(item, service_name, errors, context) for item in value]
    return value


def convert_classifier(
    classifier: dict[str, Any], service_name: str, errors: list[str], context: str
) -> dict[str, Any]:
    # The wire-form "extraKeys" is a target-CR concept this converter
    # introduces; a legacy classifier that already uses that literal key name
    # would silently collide with it below -- reject rather than guess which
    # one wins.
    if "extraKeys" in classifier:
        errors.append(f"{context} already has a literal 'extraKeys' key; rename it before migrating")
    converted: dict[str, Any] = {}
    extra_keys: dict[str, Any] = {}
    for key, value in classifier.items():
        if key == "extraKeys":
            continue
        if key in RESERVED_CLASSIFIER_KEYS:
            if key == "customKeys":
                # customKeys is itself a nested object, not a scalar classifier value --
                # its own shape is whatever the caller (convert_nested_classifiers, for a
                # sourceClassifier) or the target CRD requires, not checked here.
                converted[key] = value
            elif not isinstance(value, str):
                # Every other reserved classifier key (microserviceName, scope, namespace,
                # tenantId) is a plain string field on the target CRD -- a numeric or
                # otherwise non-string legacy value would flow straight through into the
                # generated CR and only be rejected by the API server at apply time.
                errors.append(f"{context}.{key} must be a string, got {type(value).__name__}")
                converted[key] = value
            elif key == "microserviceName":
                converted[key] = normalize_service_template(value, service_name)
            else:
                converted[key] = value
        else:
            # Legacy classifiers are open maps.  The target CRD preserves
            # arbitrary JSON values under extraKeys.
            extra_keys[key] = value
    if extra_keys:
        converted["extraKeys"] = extra_keys
    return converted


def normalize_service_template(value: str, service_name: str) -> str:
    if value.strip() in {"{{$SERVICE_NAME}}", "{{ $SERVICE_NAME }}", "${SERVICE_NAME}"}:
        return service_name
    return value


def coerce_bool(value: Any) -> Any:
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered == "true":
            return True
        if lowered == "false":
            return False
    return value


def target_metadata(
    old_metadata: dict[str, Any],
    args: argparse.Namespace,
    default_prefix: str,
    doc_index: int,
    item_index: int,
    errors: list[str],
    disambiguate_parent: bool = False,
    override_name: str | None = None,
    is_wrapper: bool = False,
) -> dict[str, Any]:
    namespace = old_metadata.get("namespace")
    if namespace is not None and not isinstance(namespace, str):
        # metadata.namespace is a string field on every Kubernetes resource; a legacy
        # source carrying a non-string value (e.g. a YAML/JSON source authored with a bare
        # number) would otherwise flow straight into the generated CR and be rejected by
        # the API server at apply time, long after this converter reported success.
        errors.append(f"metadata.namespace must be a string, got {type(namespace).__name__}")
        namespace = None
    metadata = {
        "name": resource_name(
            old_metadata,
            args,
            default_prefix,
            doc_index,
            item_index,
            disambiguate_parent=disambiguate_parent,
            override_name=override_name,
        ),
        "namespace": namespace or args.namespace,
    }
    # Carry labels/annotations forward verbatim rather than dropping them: they are
    # ordinary metadata every Kubernetes resource supports, and deployment tooling
    # (Argo CD tracking labels, policy-engine annotations, ...) may depend on them
    # surviving onto the generated CR. reject_dropped_metadata() treats both keys as
    # always-preserved and never flags them, so a malformed value (not a mapping, or a
    # mapping with a non-string value -- Kubernetes labels/annotations are always
    # string-to-string) must be caught here instead, or it is silently omitted with no
    # error at all.
    for key in ("labels", "annotations"):
        value = old_metadata.get(key)
        if value is None:
            continue
        if not isinstance(value, dict):
            errors.append(f"metadata.{key} must be an object, got {type(value).__name__}")
            continue
        bad_values = sorted(k for k, v in value.items() if not isinstance(v, str))
        if bad_values:
            errors.append(f"metadata.{key} values must be strings; non-string at key(s): {', '.join(bad_values)}")
            continue
        if key == "labels" and is_wrapper:
            # Only the kind: DBaaS wrapper's own labels are filtered -- a direct,
            # non-wrapper DbPolicy/DatabaseDeclaration carrying a same-named label
            # is a real, unrelated label (see WRAPPER_ONLY_LABELS) and is preserved.
            value = {k: v for k, v in value.items() if k not in WRAPPER_ONLY_LABELS}
        if value:
            metadata[key] = value
    return metadata


def resource_name(
    old_metadata: dict[str, Any],
    args: argparse.Namespace,
    default_prefix: str,
    doc_index: int,
    item_index: int,
    disambiguate_parent: bool = False,
    override_name: str | None = None,
) -> str:
    if override_name is not None:
        # A caller-supplied override (e.g. a plan's nameOverrides entry) is
        # deliberately constructed, unlike an auto-derived default -- it may
        # freely embed a Helm expression (typically ".Release.Name", for a
        # release-specific name) alongside literal text; the whole-template
        # restriction below exists only to stop *automatically assembling*
        # such a mix from untrusted pieces. An override's rendered value is
        # instead checked by the caller's render-time DNS-1123 validation.
        return override_name if is_templated(override_name) else sanitize_name(override_name)

    old_name = old_metadata.get("name")
    if old_name:
        name = f"{old_name}-{item_index}" if disambiguate_parent else str(old_name)
    else:
        prefix = args.name_prefix or default_prefix
        name = f"{prefix}-{doc_index}-{item_index}"

    if is_templated(name):
        if is_whole_template(name):
            return name
        # A templated scope/logical name mixed with literal text (e.g. the
        # "-2" multi-declaration suffix, or database_name_hint's own
        # "<scope>-<type>-db" shape) cannot be checked for a valid rendered
        # name and must never be produced automatically.
        raise TemplatedNameRequired(name)
    return sanitize_name(name)


def label_value(metadata: dict[str, Any], key: str) -> Any:
    labels = metadata.get("labels")
    if isinstance(labels, dict):
        return labels.get(key)
    return None


def reject_unknown_fields(
    source: dict[str, Any],
    known_fields: set[str],
    context: str,
    errors: list[str],
) -> None:
    # An unrecognized field on a legacy declaration/policy is exactly the
    # silent-data-loss risk this converter exists to close -- block instead
    # of dropping it with a warning the caller can ignore.
    unknown = sorted(set(source) - known_fields)
    if unknown:
        errors.append(f"{context} has unsupported fields that would be dropped: {', '.join(unknown)}")


def reject_dropped_metadata(metadata: dict[str, Any], context: str, errors: list[str]) -> None:
    # name/namespace/labels/annotations are preserved (PRESERVED_METADATA_FIELDS) and
    # Kubernetes-managed fields are silently safe to drop (SILENTLY_DROPPED_METADATA_FIELDS,
    # regenerated by the API server for the new resource). Anything else is a field this
    # converter does not recognize at all -- that ambiguity blocks instead of warning,
    # consistent with the package's fail-closed rule that ambiguity never gets resolved by
    # a warning acknowledgement. A malformed (non-object) labels/annotations value is
    # caught separately, in target_metadata(), since this function only sees field names.
    dropped = sorted(
        set(metadata) - PRESERVED_METADATA_FIELDS - SILENTLY_DROPPED_METADATA_FIELDS
    )
    if dropped:
        errors.append(f"{context} metadata fields would be dropped: {', '.join(dropped)}")


def reject_duplicate_resources(
    resources: list[dict[str, Any]], errors: list[str], *, root: str = ""
) -> None:
    # Called once per output root by a multi-root caller, so two independent
    # roots may legitimately reuse the same generated name -- only a
    # collision within one root's own resource list is rejected. A duplicate
    # identity would silently overwrite one CR with another when applied, so
    # this blocks instead of warning.
    seen: set[tuple[str, str, str]] = set()
    prefix = f"{root}: " if root else ""
    for resource in resources:
        metadata = resource.get("metadata") or {}
        identity = (
            str(resource.get("kind") or ""),
            str(metadata.get("namespace") or ""),
            str(metadata.get("name") or ""),
        )
        if identity in seen:
            errors.append(
                f"{prefix}duplicate generated resource kind={identity[0]} "
                f"namespace={identity[1]} name={identity[2]}"
            )
        seen.add(identity)


def sanitize_name(value: str) -> str:
    # Callers resolve templating (whole-template passthrough vs
    # TemplatedNameRequired for a mixed value) before ever reaching here; this
    # function only slugs a fully concrete name.
    value = value.lower()
    value = re.sub(r"[^a-z0-9-]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "dbaas-resource"


def dump_yaml_documents(resources: list[dict[str, Any]]) -> str:
    if yaml is not None:
        return "---\n" + "---\n".join(
            yaml.safe_dump(resource, sort_keys=False, allow_unicode=False) for resource in resources
        )
    return "---\n" + "---\n".join(dump_yaml(resource) for resource in resources)


def dump_yaml(value: Any, indent: int = 0) -> str:
    spaces = " " * indent
    if isinstance(value, dict):
        lines: list[str] = []
        for key, nested in value.items():
            formatted_key = json.dumps(str(key))
            if isinstance(nested, (dict, list)):
                if nested:
                    lines.append(f"{spaces}{formatted_key}:")
                    lines.append(dump_yaml(nested, indent + 2).rstrip("\n"))
                else:
                    empty_value = "{}" if isinstance(nested, dict) else "[]"
                    lines.append(f"{spaces}{formatted_key}: {empty_value}")
            else:
                lines.append(f"{spaces}{formatted_key}: {format_scalar(nested)}")
        return "\n".join(lines) + "\n"
    if isinstance(value, list):
        lines = []
        for item in value:
            if isinstance(item, (dict, list)):
                if item:
                    lines.append(f"{spaces}-")
                    lines.append(dump_yaml(item, indent + 2).rstrip("\n"))
                else:
                    empty_value = "{}" if isinstance(item, dict) else "[]"
                    lines.append(f"{spaces}- {empty_value}")
            else:
                lines.append(f"{spaces}- {format_scalar(item)}")
        return "\n".join(lines) + "\n"
    return f"{spaces}{format_scalar(value)}\n"


def format_scalar(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if value is None:
        return "null"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if math.isnan(value):
            return ".nan"
        if math.isinf(value):
            return ".inf" if value > 0 else "-.inf"
        text = repr(value)
        if "e" in text.lower():
            mantissa, exponent = re.split(r"[eE]", text, maxsplit=1)
            if "." not in mantissa:
                mantissa += ".0"
            return f"{mantissa}e{exponent}"
        return text
    return json.dumps(str(value))


if __name__ == "__main__":
    raise SystemExit(main())
