apiVersion: dbaas.netcracker.com/v1
kind: NamespaceBalancingRule
metadata:
  name: namespace-balancing-rules
  namespace: dbaas-system
spec:
  rules:
    - name: pg-namespace-rule
      type: postgresql
      physicalDatabaseId: postgresql-sample
      order: 0
    - name: mongo-namespace-rule
      type: mongodb
      physicalDatabaseId: mongodb-sample
      order: 1
