name: Build on Commit

on:
  - push

jobs:
  tag:
    name: Construct tag name
    runs-on: ubuntu-latest
    steps:
      - id: tag
        run: echo "name=dbaas-aggregator-$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_OUTPUT
    outputs:
      name: ${{ steps.tag.outputs.name }}
  mvn:
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    needs: [ tag ]
    with:
      maven-command: "--batch-mode deploy -Dgpg.skip=true org.sonarsource.scanner.maven:sonar-maven-plugin:${{ vars.SONAR_PLUGIN_VERSION }}:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}"
      server-id: github
      java-version: 21
      artifact-id: ${{ needs.tag.outputs.name }}
      upload-artifact: true
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  call-docker-publish:
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    needs: [ tag, mvn ]
    with:
      artifact-id: ${{ needs.tag.outputs.name }}
      download-artifact: true
