name: Build on Commit

on:
 - push

jobs:
    mvn:
        uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
        with:
            maven-command: "--batch-mode deploy -Dgpg.skip=true"
            server-id: github
            java-version: 21
            artifact-id: "dbaas-aggregator"
            upload-artifact: true
        secrets:
            maven-token: ${{ secrets.GITHUB_TOKEN }}
    call-docker-publish:
        needs: mvn
        uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
        with:
            ref: "main"
            artifact-id: "dbaas-aggregator"
            context: "."
            dry-run: false
            download-artifact: true
            component: '[
                           {"name": "dbaas-aggregator", "file": "./Dockerfile", "context": "."}
                        ]'
