---
name: Release And Publish Docker Artifact

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.3
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ github.event.inputs.version }}
          check-tag: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build JAR artifact
        run: mvn clean package -DskipTests
        working-directory: dbaas
        env:
          MAVEN_USERNAME: ${{ secrets.maven-username }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: dbaas
          path: |
            dbaas/dbaas-aggregator/target/lib
            dbaas/dbaas-aggregator/target/dbaas-aggregator-*-runner.jar
          if-no-files-found: error
          retention-days: 1
  
      - name: Build and Publish Docker Image
        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.3
        with:
          ref: v${{ inputs.version }}
          download-artifact: true
          download-artifact-path: ./artifacts
          component: |
            [
              {
                "name": "default", 
                "file": "dbaas/Dockerfile", 
                "context": "./artifacts/dbaas"
              }
            ]
          platforms: linux/amd64,linux/arm64
          dry-run: ${{ github.event.inputs.dry-run == 'true' }}            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      
      - name: Build and Publish Validation Docker Image
        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.3
        with:
          ref: v${{ inputs.version }}
          component: |
            [
              {
                "name": "default", 
                "file": "validation-image/Dockerfile", 
                "context": "./validation-image"
              }
            ]
          platforms: linux/amd64,linux/arm64              
          dry-run: ${{ github.event.inputs.dry-run == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    

      - name: Delete Tag in case of Dry Run
        if: ${{ github.event.inputs.dry-run == 'true' }}
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.3
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ github.event.inputs.version }}
          delete-tag: true

  github-release:
    needs: [build]
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v1.0.3
    with:
      version: ${{ github.event.inputs.version }}
      publish: ${{ github.event.inputs.dry-run == 'false' }}
