name: Go Build

run-name: >
  Build —
  ${{ github.event_name == 'push' && format('push [{0}]', github.event.head_commit.message) || '' }}
  ${{ github.event_name == 'pull_request' && format('PR ({0}) [{1}]', github.head_ref, github.event.pull_request.title) || '' }}

on:
  push:
    branches:
      - main
    paths:
      - 'dbaas-operator/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'dbaas-operator/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    uses: Netcracker/qubership-core-infra/.github/workflows/generic-go-build.yaml@v2.3.0
    with:
      install-envtest: true
      envtest-version: latest
      docker-config-file: 'docker-go-dev-config.json'
      # sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets: inherit
