---
name: Maven, Docker & Github Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Create Tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.7
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ inputs.version }}
          check-tag: true

  mvn-build:
    needs: create-tag
    uses: netcracker/qubership-core-infra/.github/workflows/generic-maven-build.yaml@v2.0.0
    with:
      upload-artifact: true
      ref: "refs/tags/v${{ inputs.version }}"
      maven-command: ${{ inputs.dry-run && 'verify' || 'deploy' }}
      java-version: 21

  docker-build:
    needs: mvn-build
    uses: netcracker/qubership-core-infra/.github/workflows/docker-build.yaml@v2.0.0
    with:
      ref: "refs/tags/v${{ inputs.version }}"
      dry-run: ${{ inputs.dry-run }}

  cleanup-on-dry-run:
    needs: docker-build
    if: ${{ inputs.dry-run }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.7
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ inputs.version }}
          delete-tag: true

  cleanup-on-failure:
    needs: [create-tag, mvn-build, docker-build]
    if: ${{ failure() && needs.create-tag.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete Tag on Failure
        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.7
        with:
          ref: ${{ github.ref }}
          tag-name: v${{ inputs.version }}
          delete-tag: true

  github-release:
    needs: [ docker-build ]
    if: ${{ !inputs.dry-run }}
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v1.0.7
    with:
      version: ${{ inputs.version }}
      publish: true
