---
name: Maven build

on:
  push:
    paths-ignore:
      - 'dbaas-operator/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - 'dbaas-operator/**'

jobs:
  mvn:
    uses: netcracker/qubership-core-infra/.github/workflows/generic-maven-build.yaml@v2.2.1
    with:
      upload-artifact: true
      java-version: 21
